import guideIndexJson from '@/data/guide-index.json';
import type { GuideSummary } from './guide-nav';

export type { GuideSummary };

/**
 * Every guide minus body/steps/tip/warning (~430 KB gzipped), generated by
 * scripts/generate-guide-data.mjs. For list and filter pages. The guide page
 * itself does not need it — its prev/next/related links arrive with the guide.
 */
export const guideIndex = guideIndexJson as GuideSummary[];
