import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { SEOHead } from '@/components/SEOHead';
import { PageBreadcrumb } from '@/components/PageBreadcrumb';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Banknote, ChevronRight, ShieldCheck, Bell, Lock, Phone,
  AlertTriangle, type LucideIcon, Printer,
} from 'lucide-react';

interface SafetyStep {
  id: string;
  title: string;
  detail: string;
  link?: { label: string; href: string };
}

interface Section {
  id: string;
  title: string;
  icon: LucideIcon;
  items: SafetyStep[];
}

const SECTIONS: Section[] = [
  {
    id: 'login',
    title: 'Lock down login',
    icon: Lock,
    items: [
      {
        id: 'l1',
        title: 'Use a passphrase that nothing else uses',
        detail: 'Four random words plus a couple of digits — generated by a tool, never reused on other sites. Run yours through the breach check linked below.',
        link: { label: 'Password Health Check', href: '/tools/password-health' },
      },
      {
        id: 'l2',
        title: 'Turn on two-factor authentication (2FA)',
        detail: 'In your bank app: Profile or Security → Two-step verification → ON. Pick "authenticator app" if available — text codes can be defeated by SIM swap. Authy and Google Authenticator are both free.',
      },
      {
        id: 'l3',
        title: 'Set up biometric unlock on the app',
        detail: 'Face ID or fingerprint to open the app — every major US bank supports it. Faster than typing the password every time, and the password becomes less exposed.',
      },
      {
        id: 'l4',
        title: 'Bookmark the bank\'s real site',
        detail: 'Type the address into the browser exactly once, bookmark it, and use that bookmark forever. Never click a "log in here" link in an email — that is the most common way phishing scams steal banking passwords.',
      },
    ],
  },
  {
    id: 'alerts',
    title: 'Turn on the right alerts',
    icon: Bell,
    items: [
      {
        id: 'a1',
        title: 'Alert on every transaction over $1',
        detail: 'In the app: Notifications → Account alerts → "Any debit/credit card purchase". Some banks let you set a minimum — set it to $1 so you see everything. The first sign of fraud is usually a small test charge.',
      },
      {
        id: 'a2',
        title: 'Alert on every login from a new device',
        detail: 'Settings → Security → "Notify me of sign-ins from new devices". If you ever get one of these and it was not you, change the password immediately.',
      },
      {
        id: 'a3',
        title: 'Alert on bank transfers and Zelle / Venmo / Cash App',
        detail: 'These are how scammers move money out fastest. Get an alert the moment one is initiated — not only when it completes. Some banks call this "Outgoing wire alert" or "Pending Zelle".',
      },
      {
        id: 'a4',
        title: 'Set a daily transfer limit',
        detail: 'Banks let you cap the daily amount that can leave your account. $500/day is plenty for normal use and stops a scammer from draining you in one shot. Raise it temporarily on the rare day you need to.',
      },
    ],
  },
  {
    id: 'protect',
    title: 'Protect against the common scams',
    icon: ShieldCheck,
    items: [
      {
        id: 'p1',
        title: 'Never give a "verification code" by phone',
        detail: 'No real bank will ever call and ask you to read back the 6-digit code that landed on your phone. That code is what the scammer needs to take over your account. Hang up.',
      },
      {
        id: 'p2',
        title: 'Never move money to "keep it safe"',
        detail: 'A common scam: someone calls claiming to be the bank\'s fraud department, says your money is at risk, and tells you to wire it to a "safe account". This is always a scam. Your bank already has a safe account — yours.',
      },
      {
        id: 'p3',
        title: 'Treat Zelle and wire transfers like cash',
        detail: 'Both are essentially un-reversible. Once you send, the money is gone. Only use Zelle to send money to people you actually know — never to "buy" something or "verify" anything.',
      },
      {
        id: 'p4',
        title: 'Add a trusted contact to the account',
        detail: 'Banks let you name a "trusted contact" — a family member they can call if something looks wrong on your account (large transfer, new device login, signs of confusion). They cannot move your money — only get notified.',
      },
    ],
  },
  {
    id: 'when-something-happens',
    title: 'If something looks wrong',
    icon: Phone,
    items: [
      {
        id: 'w1',
        title: 'Call the number on the back of your card',
        detail: 'Not the number in any email, text, or pop-up. The number on your physical card is the only number you can trust. Memorize the location of that card.',
      },
      {
        id: 'w2',
        title: 'Lock the card from inside the app',
        detail: 'Every major US bank now has a "lock my card" toggle. It freezes new charges instantly while you investigate. You can unfreeze in one tap once it is sorted.',
      },
      {
        id: 'w3',
        title: 'Pull credit reports if anything is unfamiliar',
        detail: 'AnnualCreditReport.com is the only government-authorised free source. Equifax, Experian, and TransUnion each give you one free per year — pull all three.',
      },
      {
        id: 'w4',
        title: 'File at IdentityTheft.gov for an official record',
        detail: 'The FTC will build you a recovery plan and give you an "Identity Theft Report" — a document banks and credit bureaus take more seriously than a phone call.',
        link: { label: 'ID Theft Recovery Wizard', href: '/tools/id-theft-recovery' },
      },
    ],
  },
];

export default function OnlineBankingSafety() {
  const [done, setDone] = useState<Set<string>>(new Set());
  const total = SECTIONS.reduce((s, x) => s + x.items.length, 0);

  const toggle = (id: string) => {
    setDone(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const printIt = () => window.print();

  return (
    <>
      <SEOHead
        title="Online Banking Safety Setup"
        description="A free, plain-English checklist for locking down your bank app — passwords, 2FA, alerts, daily limits, and a trusted contact. Plus what to do the moment something looks wrong."
        path="/tools/online-banking-safety"
      />
      <Navbar />

      <main className="min-h-screen bg-background">
        <section className="bg-gradient-to-br from-emerald-50 via-background to-green-50 dark:from-emerald-950/20 dark:to-green-950/20 border-b border-border py-10 px-4 print:hidden">
          <div className="container max-w-3xl mx-auto text-center">
            <div className="flex justify-center mb-3">
              <div className="p-3 bg-emerald-500/10 rounded-full">
                <Banknote className="h-8 w-8 text-emerald-600" />
              </div>
            </div>
            <h1 className="text-3xl md:text-4xl font-bold mb-2">Online Banking Safety Setup</h1>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto">
              15 minutes today. Lock down login, set the right alerts, and know what to do if something looks wrong.
            </p>
          </div>
        </section>

        <div className="container max-w-3xl mx-auto px-4 py-8 print:hidden">
          <PageBreadcrumb segments={[{ label: 'Tools', href: '/tools' }, { label: 'Online Banking Safety' }]} />

          <Card className="border-border shadow-sm mb-6">
            <CardContent className="p-5 flex items-center justify-between flex-wrap gap-3">
              <p className="text-sm text-muted-foreground">{done.size} of {total} done</p>
              <Button onClick={printIt} variant="outline" size="sm" className="gap-2">
                <Printer className="h-4 w-4" /> Print
              </Button>
            </CardContent>
          </Card>

          <Card className="border-border bg-muted/30 mb-6">
            <CardContent className="p-5">
              <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">Skip ahead</p>
              <div className="grid sm:grid-cols-2 gap-2 text-sm">
                {SECTIONS.map(s => (
                  <a key={s.id} href={`#${s.id}`} className="flex items-center gap-2 p-2 rounded-md hover:bg-primary/10 hover:text-primary transition-colors">
                    <ChevronRight className="h-4 w-4 shrink-0" />
                    <span>{s.title}</span>
                  </a>
                ))}
              </div>
            </CardContent>
          </Card>

          {SECTIONS.map(s => {
            const Icon = s.icon;
            return (
              <section key={s.id} id={s.id} className="mb-8 scroll-mt-24">
                <div className="flex items-center gap-3 mb-3">
                  <div className="p-2 bg-primary/10 rounded-lg">
                    <Icon className="h-5 w-5 text-primary" />
                  </div>
                  <h2 className="text-xl font-bold">{s.title}</h2>
                </div>
                <Card className="border-border">
                  <CardContent className="p-5">
                    <div className="space-y-3">
                      {s.items.map(item => (
                        <label key={item.id}
                          className={`flex items-start gap-3 p-3 rounded-lg border cursor-pointer transition-all ${
                            done.has(item.id) ? 'border-green-300 bg-green-50/50 dark:bg-green-950/20' : 'border-border hover:bg-muted/40'
                          }`}>
                          <Checkbox checked={done.has(item.id)} onCheckedChange={() => toggle(item.id)} className="mt-1" />
                          <div className="flex-1">
                            <p className={`font-medium text-sm ${done.has(item.id) ? 'line-through text-muted-foreground' : ''}`}>{item.title}</p>
                            <p className="text-xs text-muted-foreground mt-1">{item.detail}</p>
                            {item.link && (
                              <Link to={item.link.href}
                                className="inline-flex items-center gap-1 mt-2 text-xs text-primary hover:underline">
                                {item.link.label} <ChevronRight className="h-3 w-3" />
                              </Link>
                            )}
                          </div>
                        </label>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              </section>
            );
          })}

          <Card className="border-amber-300 bg-amber-50 dark:bg-amber-950/20 mb-6">
            <CardContent className="p-5 flex gap-3">
              <AlertTriangle className="h-5 w-5 text-amber-600 shrink-0 mt-0.5" />
              <div className="text-sm">
                <p className="font-semibold mb-1">The rule that catches most banking scams</p>
                <p className="text-muted-foreground">
                  If anyone — caller, email, text, pop-up — pressures you to <strong>act in the next few minutes</strong> with your bank account, hang up. Real banks never put you on a clock. The scammers always do, because they cannot afford for you to call your daughter and ask her opinion first.
                </p>
              </div>
            </CardContent>
          </Card>

          <div className="mt-10 pt-8 border-t border-border">
            <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">Related</p>
            <div className="grid sm:grid-cols-3 gap-3">
              <Link to="/tools/password-health" className="p-3 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-all">
                <p className="font-medium text-sm">Password Health Check</p>
                <p className="text-xs text-muted-foreground mt-0.5">Test your password against known breaches.</p>
              </Link>
              <Link to="/tools/id-theft-recovery" className="p-3 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-all">
                <p className="font-medium text-sm">ID Theft Recovery</p>
                <p className="text-xs text-muted-foreground mt-0.5">If something has already happened.</p>
              </Link>
              <Link to="/tools/scam-message-decoder" className="p-3 rounded-lg border border-border hover:border-primary/50 hover:bg-primary/5 transition-all">
                <p className="font-medium text-sm">Scam Message Decoder</p>
                <p className="text-xs text-muted-foreground mt-0.5">Check that "your account is locked" message.</p>
              </Link>
            </div>
          </div>
        </div>

        {/* Print version */}
        <div className="hidden print:block px-8 py-6 text-sm">
          <header className="border-b-2 border-black pb-3 mb-5">
            <h1 className="text-2xl font-bold">Online Banking Safety Setup</h1>
            <p className="text-xs text-gray-600 mt-1">A 15-minute checklist from TekSure.com</p>
          </header>
          {SECTIONS.map(s => (
            <section key={s.id} className="mb-4 break-inside-avoid">
              <h2 className="font-bold uppercase tracking-wider text-xs mb-2">{s.title}</h2>
              <ul className="space-y-1">
                {s.items.map(item => (
                  <li key={item.id} className="leading-snug">
                    <span className="font-mono mr-1">☐</span>
                    <strong>{item.title}.</strong> {item.detail}
                  </li>
                ))}
              </ul>
            </section>
          ))}
          <footer className="mt-6 pt-3 border-t border-gray-300 text-xs text-gray-600">More free safety tools at TekSure.com.</footer>
        </div>
      </main>

      <Footer />
    </>
  );
}
