import {
  AppWindow,
  Apple,
  BookOpen,
  Bot,
  Brain,
  Building2,
  EyeOff,
  Gamepad2,
  Heart,
  Home,
  Landmark,
  Laptop,
  Lightbulb,
  MessageSquare,
  Monitor,
  MonitorSmartphone,
  PiggyBank,
  Shield,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Tv,
  Users,
  Wifi,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { GuideCategory } from "@/data/guides";
import { getCategoryAccent } from "@/lib/categoryAccent";

const ICON_BY_CATEGORY: Record<GuideCategory, LucideIcon> = {
  "windows-guides": Laptop,
  "mac-guides": Apple,
  "essential-skills": BookOpen,
  "tips-tricks": Lightbulb,
  "ai-guides": Bot,
  "ai-advanced": Brain,
  "safety-guides": Shield,
  "how-to": Sparkles,
  "app-guides": AppWindow,
  "health-tech": Heart,
  "phone-guides": Smartphone,
  "social-media": Users,
  "government-civic": Building2,
  "financial-tech": PiggyBank,
  "smart-home": MonitorSmartphone,
  "entertainment": Tv,
  "communication": MessageSquare,
  "life-transitions": Gamepad2,
  "internet-connectivity": Wifi,
  "online-privacy": EyeOff,
  "online-banking": Landmark,
  "buying-guides": ShoppingBag,
  "tech-explained": Monitor,
  "troubleshooting": Wrench,
  "work-from-home": Home,
};

interface GuideThumbnailProps {
  category: GuideCategory;
  /** Tailwind size class, e.g. "h-8 w-8". Defaults to h-8 w-8. */
  size?: string;
  /** Tailwind classes for the wrapper (background, padding, rounded). */
  className?: string;
  /** Tailwind color class for the icon itself. */
  iconClassName?: string;
  /** Use the category's Origin accent for the wrapper background and icon
   *  color. When set, `className` and `iconClassName` are ignored. Renders
   *  an Origin-style themed-card block for guide thumbnails. */
  useAccent?: boolean;
}

/**
 * Renders a lucide SVG icon keyed off a guide's category. Replaces the older
 * per-guide thumbnailEmoji — emoji-free UI, consistent visual weight, and
 * accessible out of the box (aria-hidden decorative mark).
 *
 * When `useAccent` is set, the wrapper paints the Origin "Themed Content
 * Card" treatment for the guide's category (e.g. Violet Haze for AI guides,
 * Ocean Glimmer for Apps & Phones, Soft Rose for Social/Entertainment).
 */
export function GuideThumbnail({
  category,
  size = "h-8 w-8",
  className = "inline-flex items-center justify-center rounded-xl bg-primary/10 p-2 shrink-0",
  iconClassName = "text-primary",
  useAccent = false,
}: GuideThumbnailProps) {
  const Icon = ICON_BY_CATEGORY[category] ?? BookOpen;

  if (useAccent) {
    const accent = getCategoryAccent(category);
    const iconColor = accent.foreground === "light" ? "text-origin-ghost" : "text-origin-slate";
    // Inline style uses the Origin accent CSS variable directly so we don't
    // need every `bg-origin-*` class generated by Tailwind's JIT scanner.
    return (
      <span
        className="inline-flex items-center justify-center rounded-2xl shrink-0 p-3"
        style={{ backgroundColor: `hsl(var(${accent.cssVar}))` }}
        aria-hidden="true"
      >
        <Icon className={`${size} ${iconColor}`} />
      </span>
    );
  }

  return (
    <span className={className} aria-hidden="true">
      <Icon className={`${size} ${iconClassName}`} />
    </span>
  );
}

/** Map a GuideCategory to its lucide icon component (for callers that need
 *  to render the icon inline without the default wrapper). */
export function iconForCategory(category: GuideCategory): LucideIcon {
  return ICON_BY_CATEGORY[category] ?? BookOpen;
}
