// Seed library for continuous-content-loop.mjs
// Each entry becomes a single-guide batch file. Add more entries here to keep
// the loop producing fresh content for longer. Slugs must be unique across the
// whole guide library (the script validates).

export const SCAM_ALERTS = [
  {
    slug: 'scam-alert-fake-medicare-card',
    title: 'Scam Alert: Fake Medicare Card Replacement Calls',
    excerpt: 'A new wave of calls claims your Medicare card needs replacing. Here is how to spot the trick and what to do.',
    category: 'safety-guides',
    tags: ['scam alert', 'medicare', 'phone scam'],
    emoji: '🛡️',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'Scammers are calling people on Medicare and saying their card has to be replaced because of a system upgrade. They ask for your Medicare number, your Social Security number, or a bank account to mail the new card. Medicare never calls people out of the blue and asks for that information. The real Medicare card is mailed for free when you first sign up, and replacements come through your online account at Medicare.gov or by calling Medicare directly at 1-800-MEDICARE.',
    steps: [
      { title: 'Hang up if a caller asks for your Medicare number', content: 'Real Medicare staff already have your number on file. A caller asking for it is the warning sign.' },
      { title: 'Call Medicare yourself', content: 'Dial 1-800-633-4227 from your own phone if you are unsure. Do not call back the number that called you.' },
      { title: 'Report the call to the FTC', content: 'Visit ReportFraud.ftc.gov and tell them what happened. Your report helps stop the next call.', tip: 'Write down the phone number that called and the time it came in.' },
    ],
  },
  {
    slug: 'scam-alert-package-delivery-text',
    title: 'Scam Alert: Fake Package Delivery Text Messages',
    excerpt: 'Texts claiming a package is stuck and needs a small fee are everywhere. Here is the safe way to check.',
    category: 'safety-guides',
    tags: ['scam alert', 'text scam', 'shipping'],
    emoji: '📦',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'A common scam text says a package from USPS, UPS, FedEx, or Amazon is delayed and asks you to pay a small redelivery fee or update your address. The link in the text leads to a fake page that steals your card number. Real shippers do not ask for fees by text. If you are expecting a package, check the tracking number on the official website you ordered from.',
    steps: [
      { title: 'Do not tap the link', content: 'Long-press the message on iPhone, or hold it on Android, and pick Delete or Report Junk.' },
      { title: 'Check tracking the safe way', content: 'Open the original email from the seller and use the tracking link there, or type usps.com / ups.com / fedex.com into your browser by hand.' },
      { title: 'Forward the text to 7726', content: 'That spells SPAM. Your phone carrier uses these reports to block bad senders.', tip: 'It is free and works on every major US carrier.' },
    ],
  },
  {
    slug: 'scam-alert-grandparent-emergency',
    title: 'Scam Alert: The Grandparent Emergency Phone Call',
    excerpt: 'A frantic call claiming your grandchild is in trouble. Slow down and follow these steps before you send any money.',
    category: 'safety-guides',
    tags: ['scam alert', 'phone scam', 'family'],
    emoji: '🆘',
    difficulty: 'Beginner',
    readTime: '5 min',
    body: 'In this scam a caller pretends to be your grandchild or a lawyer for them. They say there has been an arrest, a car accident, or a hospital visit and money is needed right away. They beg you not to tell other family members. New AI tools let scammers copy a real voice from a few seconds of video, so the voice may sound very familiar. The fix is simple: stop, hang up, and call your family member back at the number you already have.',
    steps: [
      { title: 'Pause and breathe', content: 'Real emergencies still leave time to verify. A caller pushing you to act in the next two minutes is a red flag.' },
      { title: 'Hang up and call your family', content: 'Dial the number you already have for your grandchild or their parents. Ask if everything is alright.' },
      { title: 'Set a family code word', content: 'Pick a word only your family knows. If a caller cannot say it, the call is fake.', tip: 'Pick something silly so it is easy to remember and hard to guess.' },
      { title: 'Never wire money or buy gift cards', content: 'No real lawyer, hospital, or police officer will ever ask for payment in gift cards or wire transfers.', warning: 'Once a wire transfer or gift card code is sent, the money cannot be recovered.' },
    ],
  },
  {
    slug: 'scam-alert-tech-support-popup',
    title: 'Scam Alert: Pop-Up Warnings Saying Your Computer Is Infected',
    excerpt: 'A scary pop-up with a phone number is almost always a scam. Here is how to close it and stay safe.',
    category: 'safety-guides',
    tags: ['scam alert', 'computer', 'tech support scam'],
    emoji: '⚠️',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'Microsoft, Apple, and Google never put a phone number in a pop-up warning. If a window appears with sirens, beeping, or a voice telling you to call right away, it is a scam. The goal is to get you to call and hand over remote control of your computer. Close the window and ignore the message.',
    steps: [
      { title: 'Do not call the number on the screen', content: 'No real tech company puts a phone number in a virus warning.' },
      { title: 'Close the browser', content: 'On Windows press Ctrl + W to close the tab, or hold Alt + F4 to close the window. On Mac press Command + W. If that does not work, restart the computer.' },
      { title: 'Run a real virus scan', content: 'On Windows open Settings, go to Privacy and security, then Windows Security, and run a Quick scan. On Mac open the Apple menu and pick About This Mac to confirm your software is up to date.', tip: 'Most modern computers do not need extra antivirus software.' },
    ],
  },
  {
    slug: 'scam-alert-utility-shutoff-call',
    title: 'Scam Alert: Power Company Threatens to Shut Off Your Lights',
    excerpt: 'A caller claims your power will be cut off in one hour unless you pay. Here is how to confirm it is fake.',
    category: 'safety-guides',
    tags: ['scam alert', 'phone scam', 'utility'],
    emoji: '💡',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'Utility scammers call and threaten to shut off your power, water, or gas in 30 to 60 minutes if you do not pay right away. They ask for payment by gift card, prepaid card, or money transfer app. Real utility companies mail several written notices before any shutoff and accept payment through your normal account.',
    steps: [
      { title: 'Hang up and call the number on your bill', content: 'Find your most recent bill or your utility company website and call the customer service number printed there.' },
      { title: 'Never pay by gift card', content: 'No real power, water, or gas company accepts payment in gift cards. That request alone proves the call is fake.', warning: 'Once a gift card number is read aloud the money is gone.' },
      { title: 'Report the scam', content: 'Tell the utility company so they can warn other customers, and file a report at ReportFraud.ftc.gov.' },
    ],
  },
  {
    slug: 'scam-alert-romance-app-investment',
    title: 'Scam Alert: Online Romance That Turns Into Crypto Advice',
    excerpt: 'A friendly stranger online who wants to teach you about crypto investing is the warning sign of a long-running scam.',
    category: 'safety-guides',
    tags: ['scam alert', 'romance scam', 'investment'],
    emoji: '💔',
    difficulty: 'Beginner',
    readTime: '5 min',
    body: 'This scam, sometimes called pig butchering, starts with a wrong-number text or a friendly message on Facebook, Instagram, or a dating app. After weeks of warm conversation the new friend mentions a profitable crypto trading app. They walk the victim through depositing money and showing fake profits. When the victim tries to withdraw, fees pile up and the money disappears. The FBI tracked over $5 billion in losses to this scam in one recent year.',
    steps: [
      { title: 'Be careful with strangers who slide into your messages', content: 'A wrong number text that turns into long friendly chats is a known opening move.' },
      { title: 'Never send money to someone you have not met in person', content: 'Real friends and partners do not ask for crypto deposits, gift cards, or wire transfers.' },
      { title: 'Talk it over with someone you trust', content: 'Tell an adult child, a friend, or your bank before sending any money. Scammers count on isolation.', tip: 'If a new friend asks you to keep the relationship secret, that is the moment to tell someone.' },
      { title: 'Report the loss', content: 'File a report at IC3.gov so the FBI can track the scam.' },
    ],
  },
  {
    slug: 'scam-alert-irs-arrest-warrant',
    title: 'Scam Alert: IRS Threatens Arrest Over Back Taxes',
    excerpt: 'The IRS does not call and threaten arrest. Here is how to confirm any tax notice is real.',
    category: 'safety-guides',
    tags: ['scam alert', 'irs', 'phone scam'],
    emoji: '🏛️',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'Scammers call and claim to be from the IRS, saying you owe back taxes and the police are on their way unless you pay today. The real IRS contacts people first by mail, never threatens arrest by phone, and never asks for payment in gift cards or wire transfers. Hang up and check your account directly at IRS.gov.',
    steps: [
      { title: 'Hang up', content: 'Do not stay on the line. Do not press 1 to speak to anyone.' },
      { title: 'Check your real IRS account', content: 'Visit IRS.gov and sign in to your account, or call the IRS yourself at 1-800-829-1040.' },
      { title: 'Report the call', content: 'Forward the details to phishing@irs.gov and file a report at TIGTA.gov, the office that watches for IRS impersonation.' },
    ],
  },
  {
    slug: 'scam-alert-amazon-account-suspended',
    title: 'Scam Alert: Email Says Your Amazon Account Was Suspended',
    excerpt: 'An urgent email about a suspended Amazon account is almost always a phishing trap. Here is the safe way to check.',
    category: 'safety-guides',
    tags: ['scam alert', 'email phishing', 'amazon'],
    emoji: '📧',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'Phishing emails pretend to be from Amazon and warn that your account is suspended or that a large purchase needs your approval. The link in the email leads to a fake login page that steals your password and card number. Amazon does send real account alerts, but they always show up in the Message Center inside your Amazon account. The safe way to check is to open the Amazon app or website by hand, not from the email.',
    steps: [
      { title: 'Do not tap the link in the email', content: 'Even if the message looks real, the link can lead to a fake page.' },
      { title: 'Open Amazon directly', content: 'Type amazon.com into your browser or open the Amazon app and sign in like normal. Check Your Orders and the Message Center.' },
      { title: 'Forward the email to Amazon', content: 'Send the message as an attachment to stop-spoofing@amazon.com so Amazon can take down the fake page.' },
      { title: 'Turn on two-step verification', content: 'In Amazon under Login & security, switch on Two-Step Verification so a stolen password alone is not enough.', tip: 'A text-message code is the easiest second step to set up.' },
    ],
  },
  {
    slug: 'scam-alert-zelle-bank-fraud-warning',
    title: 'Scam Alert: Bank Fraud Department Asks You to Move Money',
    excerpt: 'A caller from your bank says fraud was found and you need to move your money to keep it safe. It is a scam.',
    category: 'safety-guides',
    tags: ['scam alert', 'bank scam', 'zelle'],
    emoji: '🏦',
    difficulty: 'Beginner',
    readTime: '5 min',
    body: 'A caller pretending to be from your bank says fraud was caught and your money needs to be sent to a safe account. They may use Zelle, a wire transfer, or ask you to take out cash and deposit it into a bitcoin ATM. Real banks never ask customers to move their own money to keep it safe. Hang up and call the number on the back of your debit card.',
    steps: [
      { title: 'Hang up', content: 'Do not stay on the line, and do not press any numbers.' },
      { title: 'Call your bank yourself', content: 'Use the phone number on the back of your debit card or your last bank statement. Ask if there is any real alert on your account.' },
      { title: 'Never send money through Zelle to fix fraud', content: 'Zelle transfers are like cash. Once sent they cannot be recovered.', warning: 'A real bank will never ask you to send yourself money through Zelle, wire, or bitcoin.' },
      { title: 'Report the call', content: 'Tell your bank what happened and file a report at IC3.gov.' },
    ],
  },
  {
    slug: 'scam-alert-jury-duty-arrest',
    title: 'Scam Alert: Caller Claims You Missed Jury Duty',
    excerpt: 'A caller pretends to be a sheriff and says a fine is owed for missed jury duty. Here is the truth.',
    category: 'safety-guides',
    tags: ['scam alert', 'phone scam', 'court'],
    emoji: '⚖️',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'Scammers call and pretend to be a deputy or court officer. They say a warrant is out because you missed jury duty and that paying a fine right away will cancel the warrant. They ask for payment by gift card or money transfer app. Real courts notify jurors by mail and never accept fines by gift card. If you are unsure, call your county courthouse using a number you look up on your county website.',
    steps: [
      { title: 'Hang up', content: 'Do not give any personal information.' },
      { title: 'Look up your county court', content: 'Search your county name plus court clerk. Call the official phone number to confirm there is no warrant.' },
      { title: 'Never pay a court fine in gift cards', content: 'Courts accept checks, money orders, or in-person payment. Gift cards are always a scam sign.', warning: 'A real officer will never threaten arrest unless you pay over the phone.' },
    ],
  },
];

export const WEEKLY_TIPS = [
  {
    slug: 'weekly-tip-clean-up-phone-storage',
    title: 'Weekly Tip: Clear Out Phone Storage in Five Minutes',
    excerpt: 'Free up space on your phone without losing photos. Here is the quick weekly cleanup.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'storage', 'phone'],
    emoji: '📱',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'Phones get slow and stop taking photos when storage runs out. The fix takes about five minutes a week. The biggest space hogs are usually downloads, old text-message photos, and apps you never open. Going through them once a week keeps things smooth.',
    steps: [
      { title: 'Open Settings and look at storage', content: 'On iPhone go to Settings, then General, then iPhone Storage. On Android open Settings, then Storage. The biggest items show at the top of the list.' },
      { title: 'Delete apps you have not opened in months', content: 'Tap the app, then Delete App on iPhone or Uninstall on Android. You can always reinstall later from the App Store or Play Store.' },
      { title: 'Clear out old text-message photos', content: 'On iPhone go to Settings, then Messages, then Keep Messages, and pick 1 Year. Old photos from texts are removed and your photo library stays untouched.', tip: 'Photos you saved on purpose stay in the Photos app.' },
      { title: 'Empty Recently Deleted', content: 'In the Photos app open Albums, scroll down to Recently Deleted, and tap Delete All. Photos sit there for 30 days using up space until you empty it.' },
    ],
  },
  {
    slug: 'weekly-tip-back-up-photos-to-cloud',
    title: 'Weekly Tip: Make Sure Your Photos Are Backed Up',
    excerpt: 'A two-minute check that protects every photo on your phone if it gets lost or broken.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'photos', 'backup'],
    emoji: '☁️',
    difficulty: 'Beginner',
    readTime: '3 min',
    body: 'A backed-up photo is a safe photo. If your phone is lost, dropped in water, or stops working, the photos are still waiting for you on a new device when you sign in. Both iPhone and Android come with free cloud backup built in, but it can quietly turn itself off. A weekly check takes about two minutes.',
    steps: [
      { title: 'Check iCloud on iPhone', content: 'Open Settings, tap your name at the top, tap iCloud, then Photos. The switch for Sync this iPhone should be green.' },
      { title: 'Check Google Photos on Android', content: 'Open the Google Photos app, tap your profile picture in the top corner, and look for Backup complete. If it says Backup is off, tap Turn on backup.' },
      { title: 'Look at the date of the most recent backup', content: 'In Google Photos tap your profile picture and pick Backup details. On iPhone the Photos app shows recent uploads at the top of the Library.', tip: 'If you are running low on free storage, both Apple and Google sell extra space for a few dollars a month.' },
    ],
  },
  {
    slug: 'weekly-tip-restart-router-monthly',
    title: 'Weekly Tip: Restart Your Internet Router for Faster Wi-Fi',
    excerpt: 'A 30-second restart often fixes slow Wi-Fi and dropped connections. Here is when and how.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'wifi', 'internet'],
    emoji: '📶',
    difficulty: 'Beginner',
    readTime: '3 min',
    body: 'Internet routers are small computers and they get tired the same way a regular computer does. After a few weeks they slow down, drop connections, or stop working with new devices. A simple restart clears the memory and refreshes the link to your internet provider. Many tech support agents start every call with this exact step.',
    steps: [
      { title: 'Find the router', content: 'Look for the small box with blinking lights, usually in a corner of the living room or near a TV. The internet cable plugs into one side and a power cord into the other.' },
      { title: 'Unplug the power for 30 seconds', content: 'Pull the power cord out of the back of the router, count slowly to 30, and plug it back in. Wait two to three minutes for the lights to settle.', tip: 'If you have two boxes (a modem and a router) unplug both, plug the modem back in first, wait two minutes, then plug in the router.' },
      { title: 'Test the internet', content: 'Open a web page on your phone or computer. If it loads quickly, the restart worked. If not, call your internet provider.' },
    ],
  },
  {
    slug: 'weekly-tip-update-iphone-apps',
    title: 'Weekly Tip: Update Your Apps to Stay Safe and Fast',
    excerpt: 'App updates often fix security holes. Here is the one-minute weekly check.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'updates', 'apps'],
    emoji: '🔄',
    difficulty: 'Beginner',
    readTime: '3 min',
    body: 'App makers send out updates that fix bugs and close security holes. When apps stay out of date, they are more likely to crash and easier for scammers to break into. Both the iPhone App Store and the Android Play Store can update apps on their own, but a weekly check makes sure nothing is stuck.',
    steps: [
      { title: 'Check updates on iPhone', content: 'Open the App Store, tap your profile picture in the top right corner, and scroll down. Tap Update All if any updates are waiting.' },
      { title: 'Check updates on Android', content: 'Open the Play Store, tap your profile picture in the top right corner, then Manage apps & device. Tap Update all.' },
      { title: 'Turn on automatic updates', content: 'On iPhone go to Settings, then App Store, and switch on App Updates. On Android open Play Store, tap your profile, Settings, Network preferences, then Auto-update apps.', tip: 'Pick Wi-Fi only so updates do not use cellular data.' },
    ],
  },
  {
    slug: 'weekly-tip-strong-password-on-email',
    title: 'Weekly Tip: Lock Down Your Email First',
    excerpt: 'Email is the master key to every other account. Here is how to make sure it is really safe.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'security', 'email'],
    emoji: '🔐',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'Almost every other account, from your bank to Amazon, sends password resets to your email. That makes email the most important account to protect. A long password and two-step verification on email blocks most attacks before they start.',
    steps: [
      { title: 'Use a long password', content: 'Pick a password at least 12 characters long. A short sentence with spaces or hyphens is easy to remember and hard to guess.' },
      { title: 'Turn on two-step verification', content: 'In Gmail go to your Google Account, then Security, then 2-Step Verification. In Outlook open account.microsoft.com, then Security, then Two-step verification.' },
      { title: 'Check what devices are signed in', content: 'On the same Security page look for Your devices or Recent activity. Sign out anything you do not recognize.', tip: 'Do this once a month to catch problems early.' },
    ],
  },
  {
    slug: 'weekly-tip-bookmark-your-bank',
    title: 'Weekly Tip: Bookmark Your Bank to Avoid Fake Sites',
    excerpt: 'A saved bookmark protects you from typing the wrong web address into a fake bank login page.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'safety', 'banking'],
    emoji: '🔖',
    difficulty: 'Beginner',
    readTime: '3 min',
    body: 'Scammers buy web addresses that look almost like real bank addresses. A small typo can land you on a fake page that copies your password. The fix takes one minute: bookmark the real bank website on your computer or phone, and use the bookmark every time. The bookmark always points to the real site.',
    steps: [
      { title: 'Open your real bank website', content: 'Find the web address on the back of your debit card or on a bank statement. Type it into your browser by hand the first time.' },
      { title: 'Add a bookmark', content: 'On a computer press Ctrl + D on Windows or Command + D on Mac. On iPhone tap the share button at the bottom and pick Add Bookmark. On Android tap the three-dot menu in Chrome and tap the star.' },
      { title: 'Use the bookmark from now on', content: 'Open the bookmark instead of typing or clicking links from email. The bookmark is the safest path back to your bank.', tip: 'Place the bookmark on your bookmarks bar so it is one click away.' },
    ],
  },
  {
    slug: 'weekly-tip-check-credit-report-free',
    title: 'Weekly Tip: Check Your Credit Report for Free Every Week',
    excerpt: 'A free check at the official site catches identity theft early. Here is the safe link.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'credit', 'identity'],
    emoji: '📊',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'The three big credit bureaus offer one free credit report each week through the only government-approved site, AnnualCreditReport.com. Looking at your report once in a while spots new accounts opened in your name, which is a sign of identity theft. The site is free and does not ask for a credit card.',
    steps: [
      { title: 'Open the official site', content: 'Type AnnualCreditReport.com into your browser by hand. Other look-alike sites try to charge a fee.' },
      { title: 'Pick one bureau', content: 'Choose Equifax, Experian, or TransUnion. You can request from the other two later in the year and stagger them every four months for free year-round watching.' },
      { title: 'Look for accounts you do not recognize', content: 'Scroll through the list of credit cards and loans. If anything is unfamiliar, contact the bureau and your bank right away.', tip: 'Save a copy of the report each time so you can compare to the next one.' },
    ],
  },
  {
    slug: 'weekly-tip-organize-home-screen',
    title: 'Weekly Tip: Tidy Up Your Home Screen for Faster Access',
    excerpt: 'A clean home screen makes your phone easier to use. Here is a five-minute reset.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'home screen', 'productivity'],
    emoji: '🏠',
    difficulty: 'Beginner',
    readTime: '4 min',
    body: 'A cluttered home screen makes it harder to find the apps you actually use every day. Spending five minutes once a week to move favorite apps to the front and tuck the rest away can save real time and frustration. Both iPhone and Android let you move apps with a long press.',
    steps: [
      { title: 'Pick your top six apps', content: 'Think about which apps you open daily. The phone, messages, browser, weather, camera, and email are common picks.' },
      { title: 'Move them to the first screen', content: 'Press and hold any app until it wiggles or a menu pops up. Drag your favorites to the first screen and to the dock at the bottom.' },
      { title: 'Hide the rest', content: 'On iPhone, swipe left past the last screen to the App Library. Apps still live there and can be searched anytime. On Android, drag less-used apps into a folder named Other.', tip: 'You do not have to delete apps to hide them, the App Library and folders keep them out of sight.' },
    ],
  },
  {
    slug: 'weekly-tip-test-your-smoke-alarms',
    title: 'Weekly Tip: Add a Smart Reminder for Your Smoke Alarms',
    excerpt: 'Use your phone or smart speaker to remind you to test the smoke alarms every month.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'smart home', 'safety'],
    emoji: '🚨',
    difficulty: 'Beginner',
    readTime: '3 min',
    body: 'The fire department recommends testing every smoke alarm once a month. Most people forget. Your phone or a smart speaker like an Amazon Echo or Google Nest can handle the reminder for you so it never gets missed.',
    steps: [
      { title: 'Set a monthly reminder on your phone', content: 'On iPhone open the Reminders app, tap New Reminder, type Test smoke alarms, tap the small i, and set Repeat to Monthly. On Android, open Google Calendar, tap the plus, pick Task, type the same, and set Monthly under Repeat.' },
      { title: 'Or ask a smart speaker', content: 'Say Alexa, remind me to test the smoke alarms on the first of every month or Hey Google, set a reminder for the first of the month at 10 AM to test smoke alarms.' },
      { title: 'When the reminder fires, push the test button', content: 'Hold the button on each alarm for a few seconds. A loud chirp means the battery is good. A weak chirp means it needs a new battery.', tip: 'Replace the whole alarm every 10 years even if it still chirps.' },
    ],
  },
  {
    slug: 'weekly-tip-use-large-text',
    title: 'Weekly Tip: Make Text on Your Phone Bigger Without an App',
    excerpt: 'Bigger text is built into every phone and computer. Here is how to turn it on.',
    category: 'tips-tricks',
    tags: ['weekly tip', 'accessibility', 'phone'],
    emoji: '🔍',
    difficulty: 'Beginner',
    readTime: '3 min',
    body: 'Eyes get tired faster on small text. Phones, tablets, and computers all let you make every word larger without needing an extra app or reading glasses. The change takes effect in messages, email, web pages, and most apps.',
    steps: [
      { title: 'Make text bigger on iPhone', content: 'Open Settings, tap Display & Brightness, then Text Size. Drag the slider to the right.' },
      { title: 'Make text bigger on Android', content: 'Open Settings, tap Display, then Font size. Drag the slider to the right.' },
      { title: 'Make text bigger on a Windows PC', content: 'Open Settings, tap Accessibility, then Text size. Drag the slider and pick Apply.' },
      { title: 'Make text bigger on a Mac', content: 'Open System Settings, pick Accessibility, then Display, then turn on Larger Text or use Display Zoom.', tip: 'You can change the setting back at any time, no harm done.' },
    ],
  },
];
