// guides-batch-128 — Auto-generated by creative-loop on 2026-05-05
// Topics: How to Find a Lost iPhone with Find My (Even if it is Off); Organize a Lifetime of Photos with Free Google Photos Albums

import type { Guide } from './guides';

export const guidesBatch128: Guide[] = [
  {
    slug: 'use-find-my-iphone-find-lost-phone',
    title: 'How to Find a Lost iPhone with Find My (Even if it is Off)',
    excerpt: 'Apple\'s free Find My service can locate a lost iPhone even when it is turned off or out of battery. Here is how to use it from any device.',
    category: 'phone-guides',
    tags: ['iphone', 'find-my', 'lost-phone', 'safety', 'apple', 'seniors'],
    readTime: '5 min',
    thumbnailEmoji: '📱',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `If your iPhone is missing — left at a restaurant, dropped on a walk, or stolen — Apple's free Find My service can locate it on a map within seconds. It works from any other Apple device or from any web browser at icloud.com.

If your iPhone is recent (iPhone 11 or newer running iOS 15 or later), Find My works even when the iPhone is turned off or has run out of battery. The phone broadcasts a low-power Bluetooth signal that nearby Apple devices pick up and report back to you anonymously.

Find My is on by default on every iPhone sold since 2019, but it never hurts to confirm. This guide walks through finding a lost iPhone, marking it as lost, and erasing it remotely if you cannot recover it.

(Sources: Apple Support — Find My, support.apple.com/find-my)`,
    steps: [
      {
        title: 'Confirm Find My is turned on (do this before you lose your phone)',
        content: 'On your iPhone, open the Settings app, tap your name at the top, then tap Find My. Tap "Find My iPhone" and make sure all three switches — Find My iPhone, Find My network, and Send Last Location — are turned on (green). The "Find My network" switch is the one that lets you find your phone when it is offline.',
      },
      {
        title: 'Open Find My from another device',
        content: 'If you have an iPad or another iPhone, open the Find My app on it. If you do not have another Apple device handy, go to icloud.com on any computer or phone (even an Android phone) and sign in with your Apple ID. Click the Find My icon to open the map.',
      },
      {
        title: 'Locate your iPhone on the map',
        content: 'Your iPhone will appear as a dot on the map at its last known location. The location updates as long as the phone has a network connection. Tap or click the dot to see the address and how recently the location was updated. If the phone is offline or off, the dot shows the last reported location with a small clock icon.',
        tip: 'Quick Tip: If your iPhone is at home but you cannot find it, click "Play Sound" in Find My. The phone makes a loud pinging sound for about a minute even if it is on silent — perfect for finding a phone lost between couch cushions.',
      },
      {
        title: 'Mark your iPhone as Lost',
        content: 'If your iPhone is somewhere outside your home, click "Mark As Lost" in Find My. This locks the phone with your passcode, suspends Apple Pay, and lets you display a custom message on the lock screen — for example, "If found, please call 555-1212." Anyone who finds the phone can see your message and call you, but they cannot use the phone, access your data, or sell it.',
      },
      {
        title: 'Get directions to your iPhone',
        content: 'If the location looks safe to retrieve (a friend\'s house, a restaurant, your car), click "Directions" in Find My to open Apple Maps with directions to the phone. If the location looks unsafe — a stranger\'s home, a part of town you do not visit — do not go yourself. Contact your local police and provide them the location.',
        warning: 'Never confront a thief directly. Police regularly recover stolen phones using the Find My location. Apple Support can verify the police request and assist with recovery.',
      },
      {
        title: 'Erase your iPhone if you cannot recover it',
        content: 'If you are sure your iPhone is gone for good, click "Erase This Device" in Find My. This wipes all your data so a thief cannot access your photos, messages, or accounts. The phone remains locked to your Apple ID even after the erase, so it is useless to anyone else. After erasing, contact your cellular carrier to suspend the line.',
        tip: 'Quick Tip: Even after erasing, Find My continues working — you can still see if the phone comes back online later, which is useful if police later try to recover it.',
      },
    ],
  },

  {
    slug: 'organize-photos-google-photos-albums',
    title: 'Organize a Lifetime of Photos with Free Google Photos Albums',
    excerpt: 'Google Photos can sort your photos by year, person, place, and event automatically. Here is how to use albums to organize a lifetime of memories.',
    category: 'app-guides',
    tags: ['photos', 'google-photos', 'organize', 'albums', 'family', 'seniors'],
    readTime: '6 min',
    thumbnailEmoji: '🖼️',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Google Photos is a free app and website that automatically sorts your photos by date, location, and even the people in them. If you have thousands of photos — from a phone, a digital camera, or scanned old photos — Google Photos can organize them faster than you can imagine.

The free tier includes 15 GB of storage, which is enough for roughly 5,000 high-quality photos. Beyond that, Google offers paid storage starting at $1.99 per month for 100 GB. There is no commitment — you can cancel any time without losing your photos.

Albums in Google Photos are folders you create to group photos by topic — like "Grandkids 2026," "Trip to Yellowstone," or "Mom's 80th Birthday." Albums can be shared with family members so everyone can add photos and view them together.

This guide walks through creating an album, adding photos, sharing it with family, and using Google's automatic memory features to find old photos by year and place.

(Sources: Google Photos Help — Albums, support.google.com/photos)`,
    steps: [
      {
        title: 'Install Google Photos and back up your phone photos',
        content: 'Download Google Photos from the App Store (iPhone) or Google Play (Android). Open the app and sign in with your Google account — if you do not have one, the app helps you create a free account. The app asks if you want to back up your photos. Tap "Back up & sync" to upload them to your free Google account so they are safe even if your phone is lost.',
        tip: 'Quick Tip: If you mostly take photos with an iPhone, you can use both Apple Photos and Google Photos at the same time. Many people back up to both for extra safety.',
      },
      {
        title: 'Create your first album',
        content: 'In the Google Photos app, tap the Library tab at the bottom (or the menu on a computer). Tap "New album" or the "+" button. Give the album a name like "Family 2026." Tap "Add photos" and select the photos you want in the album by tapping each one. Tap the checkmark when done.',
      },
      {
        title: 'Let Google Photos add photos automatically',
        content: 'In any album, tap the three-dot menu, then "Options," then turn on "Automatically add." Google Photos will add new photos to the album whenever it recognizes a face you choose, a place you specify, or photos within a date range you set. This works well for ongoing albums like "The Grandkids" — every new photo of them gets added automatically.',
      },
      {
        title: 'Share an album with family',
        content: 'Open the album, tap the share icon (an arrow or three connected dots), and choose how to share. You can email a link, share through Messages, or copy a link to paste anywhere. Anyone with the link can view the album, and if you turn on "Collaborate," they can add their own photos too — so a Christmas album can have photos from every family member, all in one place.',
        tip: 'Quick Tip: Shared albums are private by default — only people with the exact link can see them. The link is unguessable and not searchable on Google.',
      },
      {
        title: 'Find old photos with Memories and Search',
        content: 'On the home screen of Google Photos, you will see "Memories" cards — a slideshow of "5 Years Ago Today" or "Best of 2024." Tap any memory to see and share it. To find specific photos, use the search bar at the top — type "beach," "Mom," "Christmas," or any place or event, and Google finds matching photos using AI. It works remarkably well, even on old scanned photos.',
      },
      {
        title: 'Print photos from Google Photos',
        content: 'In the album, tap the three-dot menu, then "Order photos." You can print a photo book of the entire album (starting at about $10), order photo prints to be mailed to your home, or have prints delivered to a CVS, Walmart, or Target near you for same-day pickup. This is a meaningful gift for family members who do not use phones or computers.',
      },
    ],
  },
];
