// guides-batch-280 (recovered from main's original batch 136) — Auto-generated by creative-loop on 2026-05-05
// Topics: How to Join a Telehealth Doctor Visit on Zoom or Phone; How to Find and Cancel Hidden Subscriptions on Your Phone

import type { Guide } from './guides';

export const guidesBatch280: Guide[] = [
  {
    slug: 'use-zoom-doctor-telehealth-visit',
    title: 'How to Join a Telehealth Doctor Visit on Zoom or Phone',
    excerpt: 'Most doctors now offer video appointments. Here is how to join one on Zoom, or use a phone call instead if video is not working.',
    category: 'health-tech',
    tags: ['telehealth', 'zoom', 'doctor', 'video-visit', 'medicare', 'seniors'],
    readTime: '6 min',
    thumbnailEmoji: '🏥',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `A telehealth visit is a doctor appointment by video instead of in person. The doctor sees you on a screen, you see the doctor on yours, and you have the same kind of conversation you would have in their office — without the drive or the waiting room.

Most major insurance plans, including Medicare, cover telehealth visits the same as in-person appointments. The most common platform doctors use is Zoom (or a hospital-branded version of it like Zoom for Healthcare).

If you are intimidated by video, do not be — most telehealth platforms also let you join by phone call only, with no video at all. The doctor still gets the visit, your insurance still covers it, and you do not need any technology you do not already have.

This guide walks through joining a Zoom video visit step by step, with notes on phone-only fallback.

(Sources: Medicare.gov — Telehealth, medicare.gov/coverage/telehealth; Zoom Help Center, support.zoom.us; Health and Human Services telehealth resources, telehealth.hhs.gov)`,
    steps: [
      {
        title: 'Find the link or phone number from the doctor office',
        content: 'A few days before the appointment, you should receive an email or text message from the doctor office with a meeting link (like zoom.us/j/123456) or a phone number to call. If you have not received this 24 hours before the visit, call the office and ask for the link or phone number to be re-sent.',
        warning: 'Verify the email is from the doctor office (real domain like @stanfordhealth.org or @kaiserpermanente.org). Phishing emails sometimes pretend to be telehealth invitations to steal information.',
      },
      {
        title: 'Test your camera and microphone the day before',
        content: 'Visit zoom.us/test in any browser to run a free test meeting. Zoom checks your camera, microphone, and speaker. This takes about 2 minutes and confirms everything works before the actual appointment. If something is not working, you have time to fix it without delaying your visit.',
        tip: 'Quick Tip: A laptop with a built-in camera works best because it props up and shows your face from the right angle. A phone or tablet works too — set it on a stable surface so you do not have to hold it.',
      },
      {
        title: 'Click the Zoom link 5 minutes early',
        content: 'About 5 minutes before your appointment time, click the Zoom link in your email or text. Your browser may prompt you to download Zoom — say Yes. The first time you join Zoom, it installs in the background and takes a minute. After that, joining is instant.',
      },
      {
        title: 'Allow camera and microphone access',
        content: 'Zoom asks permission to use your camera and microphone. Click Allow on both. You may also see a button to "Join with computer audio" — click it. You will see yourself on screen and hear a tone when the doctor joins.',
      },
      {
        title: 'Wait in the virtual waiting room until the doctor arrives',
        content: 'Most doctor offices use a Zoom feature called Waiting Room. You see a screen that says "The host will let you in soon." When the doctor is ready, you will be admitted to the meeting and the doctor appears. The visit proceeds like a normal appointment — describe your symptoms, ask questions, take notes.',
      },
      {
        title: 'Join by phone if video does not work',
        content: 'Every Zoom invitation also includes a phone number you can call to join by audio only. Look in the email for "Or by Phone" — it lists a phone number and a meeting ID. Call the number, type the meeting ID followed by # when prompted, and you join the visit by voice. Your insurance covers this the same as a video visit.',
        tip: 'Quick Tip: Save the office\'s telehealth phone number in your phone contacts. The same number usually works for any future telehealth visit.',
      },
    ],
  },

  {
    slug: 'cancel-subscriptions-iphone-android',
    title: 'How to Find and Cancel Hidden Subscriptions on Your Phone',
    excerpt: 'Apple and Google make subscriptions easy to start and surprisingly hard to find. Here is how to see every active subscription and cancel any of them.',
    category: 'phone-guides',
    tags: ['subscriptions', 'iphone', 'android', 'apple', 'google', 'money', 'seniors'],
    readTime: '5 min',
    thumbnailEmoji: '📄',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Apple and Google bill many app subscriptions through your Apple ID or Google Play account. This is convenient — you do not have to enter a credit card for each app — but it also means subscriptions can pile up where you cannot easily see them. Many people are surprised to find $5 here, $10 there, all charged to a card they barely remember signing up for.

Both Apple and Google have a single screen that lists every active subscription. From that screen, you can cancel any of them with two taps. The cancellation always takes effect at the end of the current billing period, so you keep access to anything you already paid for.

This guide shows where to look on iPhone and Android, and what to do about lifetime subscriptions or "free trials" that auto-renew.

(Sources: Apple Support — Subscriptions, support.apple.com/HT202039; Google Play Help — Subscriptions, support.google.com/googleplay; FTC consumer information on auto-renewal, consumer.ftc.gov)`,
    steps: [
      {
        title: 'On iPhone: open Settings → your name → Subscriptions',
        content: 'On your iPhone, open the Settings app. Tap your name at the very top of the screen. On the next screen, tap Subscriptions. This shows every active subscription billed through Apple, the price, and the next charge date.',
      },
      {
        title: 'On Android: open Google Play → menu → Payments and subscriptions',
        content: 'On Android, open the Google Play Store app. Tap your profile icon at the top right. Tap Payments and subscriptions, then Subscriptions. This shows every active subscription billed through Google.',
      },
      {
        title: 'Review what is active and how much it costs',
        content: 'Look through the list carefully. Common surprises: trial subscriptions that turned into paid ones (Apple TV+, HBO Max, Peacock), apps you tried once and forgot about, dating apps, weather apps, and photo apps. The screen shows the price for each.',
        tip: 'Quick Tip: Add up everything you see. Many people are paying $50 or more per month in subscriptions they do not actively use. Cancelling unused ones is one of the fastest ways to lower your monthly expenses.',
      },
      {
        title: 'Tap any subscription to cancel it',
        content: 'Tap a subscription to see details. Scroll down and tap "Cancel Subscription" (Apple) or "Cancel subscription" (Google). Confirm. You will keep access until the end of the current billing period, then the app stops charging.',
      },
      {
        title: 'Watch for "free trial" auto-renewals',
        content: 'Many apps offer a free trial that requires a credit card and auto-renews into a paid subscription unless you cancel before the trial ends. To prevent surprise charges, the moment you start a trial, immediately go to Subscriptions and tap Cancel. You keep access for the full trial period, but the auto-renewal is turned off.',
        warning: 'Some companies (notably gym apps and dating apps) make cancellation deliberately confusing inside the app itself. The Apple/Google subscription screens always work, regardless of what the app shows you.',
      },
      {
        title: 'Check your bank statement for direct subscriptions',
        content: 'Some subscriptions are not billed through Apple or Google — instead, you give your credit card directly to the company (like Netflix, Spotify Family, or many magazine subscriptions). Review your monthly credit card statement for any recurring charges. Cancel directly with the company by calling their support number.',
      },
    ],
  },
];
