// guides-batch-130 — Auto-generated by creative-loop on 2026-05-05
// Topics: Save Your Favorite Places in Google Maps (and Share the List with Family); How Emergency SOS Works on iPhone (and How to Test It Safely)

import type { Guide } from './guides';

export const guidesBatch130: Guide[] = [
  {
    slug: 'use-google-maps-favorite-saved-places',
    title: 'Save Your Favorite Places in Google Maps (and Share the List with Family)',
    excerpt: 'Google Maps can save your doctor, pharmacy, favorite restaurant, and more in one tap — and share the list with family. Here is how.',
    category: 'app-guides',
    tags: ['google-maps', 'navigation', 'saved-places', 'seniors', 'family'],
    readTime: '5 min',
    thumbnailEmoji: '🗺️',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Google Maps lets you save addresses for places you visit often — your doctor's office, the pharmacy, your favorite restaurant, your daughter's house — so you can navigate to them with one tap instead of typing the address each time.

Saved places sync across your phone, tablet, and computer (anywhere you sign in to your Google account). You can also share a list of places with family members — useful for handing off "the list of places I drive to" if you ever stop driving and need someone else to know where things are.

There are no fees for any Google Maps feature. The app comes pre-installed on most Android phones and is a free download on iPhone.

This guide covers saving a place, organizing places into lists, sharing a list, and using "Home" and "Work" shortcuts that show up at the top of every search.

(Sources: Google Maps Help, support.google.com/maps)`,
    steps: [
      {
        title: 'Open Google Maps and search for a place',
        content: 'On your phone, open Google Maps. In the search bar, type the name or address of the place you want to save — for example, "Memorial Hospital" or "1234 Oak Street." Tap the result that matches.',
      },
      {
        title: 'Tap Save and pick a list',
        content: 'On the place detail page, look for the "Save" button (a bookmark icon). Tap it. Google offers a few default lists — Favorites, Want to go, Starred places — and you can create new lists by tapping "+ New list." Pick a list and the place is saved.',
        tip: 'Quick Tip: Create lists like "Doctors," "Pharmacies," and "Restaurants" to keep things organized. You can save the same place to multiple lists.',
      },
      {
        title: 'Set Home and Work for one-tap directions',
        content: 'In Google Maps, tap your profile icon (top right), then "Settings," then "Edit home or work." Type your home address and your work address (or your most common destination, like a senior center). After this, when you open Google Maps, "Home" and "Work" appear at the top of the screen — tap either for instant directions.',
      },
      {
        title: 'Share a list with family',
        content: 'Open the Saved tab (bottom of the screen on iPhone, or in the menu on Android). Tap a list. Tap the three-dot menu in the upper right and pick "Share list." You can copy a link, send by Messages, email, or any other app. Anyone with the link can view the list. They can also save it to their own Google Maps if they have an account.',
      },
      {
        title: 'View your saved places anytime',
        content: 'In Google Maps, tap the "Saved" tab. You see all your lists. Tap any list to see the places. Tap any place to get directions, see hours, or call the business. This is a fast way to find phone numbers for your doctor or pharmacy without searching the internet.',
      },
      {
        title: 'Print or export your list for offline reference',
        content: 'On a computer, sign in to Google Maps at maps.google.com. Click the menu (three lines) in the upper left, then "Your places," then the list you want. Click the three-dot menu and choose "Export list to KML." The downloaded file works in many other map apps. You can also print the page from your browser for a paper backup.',
      },
    ],
  },

  {
    slug: 'use-iphone-emergency-sos-feature',
    title: 'How Emergency SOS Works on iPhone (and How to Test It Safely)',
    excerpt: 'iPhones have built-in Emergency SOS that calls 911, alerts your family, and shares your location — even if you cannot speak. Here is how it works.',
    category: 'safety-guides',
    tags: ['iphone', 'emergency', 'sos', '911', 'safety', 'seniors', 'medical'],
    readTime: '6 min',
    thumbnailEmoji: '🆘',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Every iPhone sold since 2017 has Emergency SOS — a built-in safety feature that can call 911, share your location, and notify emergency contacts you have set up, all without you needing to dial. It works in two ways: a button shortcut you press, and an automatic crash and fall detection that triggers when sensors detect an impact.

If you have an iPhone 14 or newer, Emergency SOS also works via satellite when you have no cellular signal — useful in remote areas or during cellular outages.

This guide explains how Emergency SOS works, how to set up your medical ID and emergency contacts, and how to test the feature without accidentally calling 911 (a common worry for new users).

(Sources: Apple Support — Emergency SOS, support.apple.com/HT208076; American Red Cross emergency preparedness, redcross.org)`,
    steps: [
      {
        title: 'Set up your Medical ID first',
        content: 'Medical ID is a profile that emergency responders can view from your locked iPhone — including your medical conditions, medications, blood type, and allergies. To set it up, open the Health app on your iPhone. Tap your profile icon at the top, then Medical ID, then Edit. Fill in the relevant fields. Make sure "Show When Locked" is turned on so paramedics can see it without your passcode.',
      },
      {
        title: 'Add Emergency Contacts',
        content: 'Still in the Medical ID screen, scroll down to "Emergency Contacts." Tap "Add Emergency Contact" and select someone from your address book. Pick the relationship (Spouse, Daughter, Son, etc.). When Emergency SOS is triggered, your iPhone sends a text message to these contacts with your location and a note that an emergency call has been placed.',
        tip: 'Quick Tip: Add at least two emergency contacts — your spouse and an adult child, for example — so if one is unreachable, the other gets the alert.',
      },
      {
        title: 'Learn the SOS button shortcut',
        content: 'On any iPhone, press and hold the side button (right side, the long button) plus either volume button at the same time. After a moment, the Emergency SOS slider appears. Slide it to call 911. If you keep holding the buttons instead of releasing, the iPhone calls 911 automatically after a countdown.',
        warning: 'Do NOT actually slide to call 911 unless you are in a real emergency. Releasing the buttons before the countdown ends cancels the call.',
      },
      {
        title: 'Practice safely without calling 911',
        content: 'To practice, press and hold side button + volume up briefly — only until the SOS slider appears — then release the buttons immediately. The slider disappears and no call is placed. Do this a few times so the motion is muscle memory. You will not accidentally call 911 by releasing early — the call only goes through after the slider is dragged or after a several-second auto-call countdown.',
      },
      {
        title: 'Turn on Crash Detection (if available)',
        content: 'iPhone 14 and later have Crash Detection — they automatically call 911 if sensors detect a severe car crash. To check, open Settings, tap Emergency SOS, and confirm "Call After Severe Crash" is on. False alarms are rare but possible, especially during certain amusement park rides — the iPhone gives you 10 seconds to cancel before the call goes through.',
      },
      {
        title: 'Know how to use Satellite SOS (iPhone 14 and newer)',
        content: 'If you are out of cellular range during an emergency, the iPhone 14, 15, and 16 can connect via satellite to send a text-based emergency message. To use it, dial 911. If your iPhone cannot reach a cell tower, it offers "Emergency Text via Satellite." Tap it and follow the on-screen prompts to point your phone at the satellite. This service is free for the first two years of iPhone ownership.',
      },
    ],
  },
];
