// guides-batch-126 — Auto-generated by creative-loop on 2026-05-05
// Topics: How to Spot a Fake Tech Support Pop-Up (and What to Do); How to Set Up and Use Your Medicare Online Account

import type { Guide } from './guides';

export const guidesBatch126: Guide[] = [
  {
    slug: 'spot-fake-tech-support-popup-ads',
    title: 'How to Spot a Fake Tech Support Pop-Up (and What to Do)',
    excerpt: 'Pop-ups claiming your computer is infected and asking you to call a phone number are almost always scams. Here is how to recognize and dismiss them safely.',
    category: 'safety-guides',
    tags: ['scam', 'tech-support-scam', 'pop-up', 'safety', 'seniors', 'browser', 'malware'],
    readTime: '5 min',
    thumbnailEmoji: '🛡️',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `If a pop-up appears on your computer claiming your device is infected with a virus, displaying a Microsoft or Apple logo, and asking you to call a phone number — close it immediately. Real Microsoft, Apple, and Google support never display pop-ups with phone numbers. These are scams designed to convince you to call a fake "support" line where someone will ask for remote access to your computer or payment for fake services.

The pop-ups can look very convincing. Some make alarm sounds. Some say "Your computer has been locked." Some claim the FBI is involved. None of these are real. Closing the browser tab or window is the correct response in every case.

If you have already called a number from one of these pop-ups, do not panic. The next steps depend on what you shared. If you only spoke briefly and shared no information or payment, you are likely safe. If you allowed remote access to your computer, you should disconnect the internet, run a malware scan, and change your important passwords from a different device.

(Sources: FTC Consumer Information, consumer.ftc.gov; Microsoft Support, support.microsoft.com; AARP Fraud Watch Network, aarp.org/money/scams-fraud)`,
    steps: [
      {
        title: 'Recognize the warning signs',
        content: 'Real warnings from your computer never include a phone number to call. They never make alarm sounds or block your entire screen. They never claim law enforcement is involved. If a pop-up has any of these features — phone number, urgent countdown, alarm sound, claim of being from the FBI or Microsoft — it is a scam.',
        tip: 'Quick Tip: Microsoft Defender warnings appear in the small Windows Security app, not as full-screen browser pop-ups with phone numbers.',
      },
      {
        title: 'Close the browser without clicking anything in the pop-up',
        content: 'Do not click any button inside the pop-up — not "Close," not "OK," not "X." Some scam pop-ups have buttons that trigger more pop-ups when clicked. Instead, close the entire browser window. On Windows, press Alt + F4. On Mac, press Cmd + Q. On a phone, swipe up from the bottom of the screen and swipe the browser app away.',
        warning: 'If the browser will not close normally, force-quit it. On Windows, press Ctrl + Shift + Esc to open Task Manager, find your browser in the list, and click End Task. On Mac, press Cmd + Option + Esc to open Force Quit, select the browser, and click Force Quit.',
      },
      {
        title: 'Clear your browser cache after the pop-up is gone',
        content: 'Reopen your browser and clear the cache to remove any stored copies of the scam page. In Chrome, click the three-dot menu, then Settings, then Privacy and Security, then Clear browsing data. In Safari, click Safari in the menu bar, then Clear History. In Edge, click the three-dot menu, then Settings, then Privacy.',
      },
      {
        title: 'Run a free malware scan',
        content: 'On Windows, open Windows Security (search for it from the Start menu), click Virus and threat protection, then Quick Scan. On Mac, malware is rare but you can use the free version of Malwarebytes from malwarebytes.com if you are concerned. Both scanners are free and trusted.',
        tip: 'Quick Tip: Avoid downloading unknown "antivirus" tools from search results — many are themselves malware. Stick to Windows Security on Windows, and the official Malwarebytes site on Mac.',
      },
      {
        title: 'Report the scam to the FTC',
        content: 'Reporting helps the Federal Trade Commission build cases against the criminals running these scams. Go to reportfraud.ftc.gov and fill out the short form. You do not need any personal information about the scammer — only a brief description of what happened. This is free and takes about 5 minutes.',
      },
    ],
  },

  {
    slug: 'understand-medicare-online-account',
    title: 'How to Set Up and Use Your Medicare Online Account',
    excerpt: 'Your free Medicare.gov account lets you check claims, order replacement cards, and manage your benefits without phone calls. Here is the step-by-step setup.',
    category: 'government-civic',
    tags: ['medicare', 'health', 'government', 'account', 'seniors', 'benefits'],
    readTime: '7 min',
    thumbnailEmoji: '🏥',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Medicare.gov is the official US government website for Medicare beneficiaries. Setting up a free online account lets you check the status of your claims, order a replacement Medicare card, manage your prescriptions and providers, and keep an eye on your benefits without sitting on hold for an hour.

There is no cost. There are no paid features. The only Medicare website you need is medicare.gov — any site charging fees for Medicare services is unofficial and likely a scam.

Setting up the account takes about 10 minutes. You will need your red, white, and blue Medicare card, your Social Security number, and an email address. If you do not have an email address yet, you can create a free Gmail account at gmail.com first.

(Sources: Medicare.gov, medicare.gov; Social Security Administration, ssa.gov; AARP Medicare Resource Center, aarp.org/health/medicare-insurance)`,
    steps: [
      {
        title: 'Go to medicare.gov and start the account creation',
        content: 'Type medicare.gov directly into your browser address bar. Do not click on Medicare links from emails or search ads, as some of these lead to scam sites. On the official site, click the "Log in or create account" button at the top right of the page, then click "Create an account."',
        warning: 'Real Medicare websites end in .gov. If a site claims to be Medicare but ends in .com or .net, it is not the official site.',
      },
      {
        title: 'Verify your identity with Login.gov or ID.me',
        content: 'Medicare uses two trusted federal identity verification services — Login.gov and ID.me. Either works. You will need to provide your name, address, Social Security number, and Medicare number (from your card). The site may ask you to take a photo of your driver license or state ID with your phone for verification.',
        tip: 'Quick Tip: If you already have a Login.gov account from filing taxes online or another government service, you can sign in with the same email and password.',
      },
      {
        title: 'Create a strong password',
        content: 'Use a password you do not use anywhere else. A good Medicare password is at least 12 characters and uses a mix of words, numbers, and a symbol. Write it down somewhere safe — a notebook in a drawer is fine, as long as no strangers have access to it. Do not share it with anyone, including family members claiming to call from Medicare.',
      },
      {
        title: 'Tour the dashboard and find your claims',
        content: 'After signing in, you land on the My Medicare dashboard. Click "Claims and care" to see every doctor visit and procedure billed to Medicare in the past two years. Each claim shows the date, the provider, what was billed, what Medicare paid, and what you owe. Compare these to the bills you receive from doctors to catch billing errors.',
        tip: 'Quick Tip: Medicare claims appear within 30 to 90 days of the visit. If a claim does not appear after 90 days, contact the doctor office to confirm they billed correctly.',
      },
      {
        title: 'Order a replacement Medicare card if needed',
        content: 'If your card is lost, damaged, or stolen, you can order a replacement online at no cost. From the dashboard, click "Cards and certificates," then "Order a Medicare card." The replacement arrives by mail in about 30 days. While you wait, you can print a temporary version from the same page.',
      },
      {
        title: 'Set up Medicare email alerts',
        content: 'In the Settings menu of your account, you can turn on email alerts for new claims, plan changes, and important Medicare deadlines. This is optional but useful — if you see a claim alert email for a doctor visit you do not remember, that is an early warning sign of medical identity theft.',
      },
    ],
  },
];
