// guides-batch-329 — Auto-generated by 90-day sprint task on 2026-07-26
// Topics: Toll road text scams; Medication reminders; Live Captions for phone calls;
// Freezing your credit at all three bureaus; Apple Check In; Amazon Subscribe & Save

import type { Guide } from './guides';

export const guidesBatch329: Guide[] = [
  {
    slug: 'toll-road-text-scam-warning',
    title: 'The Toll Road Text Scam: How to Spot and Avoid It',
    excerpt: 'Fake texts claiming you owe money on a toll road (E-ZPass, SunPass, FasTrak) are one of the most common scams in the country right now. Here is how to tell a real toll notice from a fake one.',
    category: 'safety-guides',
    tags: ['scam', 'toll', 'text message', 'phishing', 'e-zpass', 'fraud'],
    readTime: '5 min',
    thumbnailEmoji: '🚧',
    publishedAt: '2026-07-26',
    lastVerifiedAt: '2026-07-26',
    difficulty: 'Beginner',
    body: `A text message arrives saying something like "You have an unpaid toll of $6.99. Pay now to avoid a late fee and legal action." It includes a link and looks like it came from E-ZPass, SunPass, FasTrak, or another toll agency. This is almost always a scam.

The FBI's Internet Crime Complaint Center (IC3) has received hundreds of thousands of reports about this exact scam. It works because it creates urgency (a late fee, "legal action") and pretends to be a real toll agency people recognize, even if they have never driven through a toll in their life.

The link in the text leads to a fake payment page that looks like a real toll agency website. If you enter your card number, the scammers steal it. Some versions also ask for your Social Security number or driver's license number "for verification," which is a major red flag — real toll agencies never ask for this over text.

The safest response is to never tap the link. Real toll agencies do not send payment demands by text message with urgent deadlines. If you are worried you might actually owe a toll, go directly to your toll agency's official website by typing the address yourself, or call the number printed on your toll account statement — not a number from the text.

(Sources: FBI Internet Crime Complaint Center — ic3.gov; Federal Trade Commission — consumer.ftc.gov)`,
    steps: [
      {
        title: 'Do not tap the link in the text',
        content: 'No matter how official it looks, do not tap any link in an unexpected toll text. Tapping the link can take you to a fake payment page designed to steal your card information, even if you do not enter anything yet on some more advanced scam pages.',
      },
      {
        title: 'Check the sender and wording for red flags',
        content: 'Scam texts often come from random phone numbers or email-style addresses rather than a company short code. Watch for urgent language like "final notice," "pay immediately," or "avoid legal action" — real toll agencies use calmer, more routine language and give you weeks to pay, not hours.',
        warning: 'Real toll agencies never ask for your Social Security number, driver\'s license number, or bank login over text. If a text asks for any of these, it is a scam.',
      },
      {
        title: 'Check your account directly instead',
        content: 'If you are unsure whether you owe a toll, open a web browser and type your toll agency\'s website address yourself (for example, ezpassva.com or sunpass.com) rather than using any link from the text. Log in to your real account to check your balance, or call the customer service number printed on a past statement or your toll transponder.',
      },
      {
        title: 'Report the text',
        content: 'Forward the scam text to 7726 (SPAM) to report it to your phone carrier. You can also file a report at ic3.gov (FBI) or reportfraud.ftc.gov (Federal Trade Commission). Reporting helps investigators track and shut down these scam networks.',
      },
      {
        title: 'Delete the text',
        content: 'Once you have reported it, delete the message. If you accidentally tapped the link and entered card information, call your bank or card issuer immediately to cancel the card and watch your statements closely for unauthorized charges.',
      },
    ],
  },

  {
    slug: 'set-up-medication-reminders-iphone-android-2026',
    title: 'How to Set Up Medication Reminders on Your iPhone or Android',
    excerpt: 'Forgetting a dose or accidentally doubling up is one of the most common medication mistakes. Your phone can remind you every time, for free, without any extra app.',
    category: 'health-tech',
    tags: ['medication', 'reminders', 'health', 'alarms', 'seniors', 'iphone', 'android'],
    readTime: '6 min',
    thumbnailEmoji: '💊',
    publishedAt: '2026-07-26',
    lastVerifiedAt: '2026-07-26',
    difficulty: 'Beginner',
    body: `Both iPhone and Android phones have a free, built-in way to remind you when it is time to take medication — no app download required. On iPhone, the Reminders app has a dedicated "Medication" reminder type that even tracks refill dates. On Android, the built-in Clock app's alarms work well, and Google's Reminders feature inside Google Assistant can also be used by voice.

Setting this up takes about 10 minutes for all your medications, and after that, your phone handles it automatically every day. This is especially useful for medications taken at specific times relative to food, or medications where missing a dose matters (like blood thinners or blood pressure medication).

This guide covers the iPhone Medication feature first, then the Android alarm method, since the two phone types handle this differently.

(Sources: Apple Support — support.apple.com/guide/iphone/track-your-medications; Google Support — support.google.com)`,
    steps: [
      {
        title: 'iPhone: Open the Health app and add your medications',
        content: 'Open the Health app (white icon with a red heart). Tap "Browse" at the bottom, then "Medications." Tap "Add a Medication" and either scan the pill bottle with your camera or type the name. The app will suggest matching medications from a database — pick the correct one, strength, and form (pill, liquid, etc.).',
      },
      {
        title: 'Set the schedule and reminder times',
        content: 'After adding a medication, you will be asked how often you take it (once a day, twice a day, as needed, etc.) and at what times. Enter the exact times you normally take each dose. The app creates a reminder notification for each one automatically.',
        tip: 'Quick Tip: If you take a medication with food, set the reminder time for 15-20 minutes before your usual mealtime so you have time to prepare.',
      },
      {
        title: 'iPhone: Log doses as you take them',
        content: 'When a medication reminder notification appears, tap it to mark the dose as "Taken" or "Skip." This builds a simple history you can look back on, which is helpful when talking to your doctor or pharmacist about whether you have been consistent.',
      },
      {
        title: 'Android: Set a repeating alarm for each medication time',
        content: 'Open the Clock app. Tap "Alarm," then the plus (+) button. Set the time for your first dose. Tap the alarm name field and type the medication name (like "Blood Pressure Pill — 8am") so the label reminds you exactly what to take. Tap "Repeat" and choose every day. Save the alarm, then repeat this process for each additional dose time.',
      },
      {
        title: 'Android: Try voice reminders as a backup',
        content: 'You can also say "Hey Google, remind me to take my medication at 8am every day" to your phone or a Google-connected smart speaker. Google Assistant will confirm and set a recurring reminder without you needing to open any app.',
      },
      {
        title: 'Consider a physical pill organizer alongside phone reminders',
        content: 'A weekly pill organizer (labeled Sunday through Saturday, morning/evening) is still one of the best tools for catching missed or doubled doses at a glance, and it works well paired with phone reminders as a backup. Most pharmacies sell these for a few dollars.',
      },
    ],
  },

  {
    slug: 'turn-on-live-captions-phone-calls',
    title: 'How to Turn On Live Captions for Phone Calls (iPhone and Android)',
    excerpt: 'Live Captions show a real-time text transcript of what the other person is saying during a phone call, right on your screen. Great for noisy environments or hearing difficulty.',
    category: 'health-tech',
    tags: ['live captions', 'accessibility', 'hearing', 'phone calls', 'iphone', 'android'],
    readTime: '5 min',
    thumbnailEmoji: '💬',
    publishedAt: '2026-07-26',
    lastVerifiedAt: '2026-07-26',
    difficulty: 'Beginner',
    body: `Live Captions is a free, built-in accessibility feature on both iPhone and Android that shows a scrolling text transcript of a phone call directly on your screen as the other person talks. It works entirely on your phone — no internet connection or account needed for the captions themselves — and it also works for video calls, streamed videos, and voicemail on many phones.

This is genuinely useful even for people without hearing loss: it helps in loud rooms, when a caller has a strong accent or fast speech, or when you want a quick way to review what was just said without asking someone to repeat themselves.

The caption text stays completely private and is not sent anywhere or saved by default. It disappears when you end the call.

(Sources: Apple Support — support.apple.com/en-us/111876; Google Accessibility — support.google.com/accessibility)`,
    steps: [
      {
        title: 'iPhone: Turn on Live Captions',
        content: 'Open Settings, tap Accessibility, then scroll to and tap "Live Captions (Beta)." Turn on the toggle at the top. A confirmation screen explains how it works — tap "Turn On Live Captions" to confirm. Note: this feature requires an iPhone 11 or later.',
      },
      {
        title: 'iPhone: Use captions during a call',
        content: 'Once turned on, a caption window automatically appears near the bottom of the screen during any phone or FaceTime call, showing text of what the other person says. You can drag the caption window to reposition it, or tap and hold to resize it for easier reading.',
        tip: 'Quick Tip: You can also turn Live Captions on and off quickly from Control Center once you add it — go to Settings → Control Center and add "Live Captions" as a shortcut.',
      },
      {
        title: 'Android: Turn on Live Caption',
        content: 'Open Settings, tap "Sound & vibration" (or "Accessibility" on some phones), then tap "Live Caption." Turn on the toggle. On many Android phones, you can also press a volume button while any audio is playing and tap the Live Caption icon that appears above the volume slider.',
      },
      {
        title: 'Android: Use captions during a call',
        content: 'During a phone call, tap the Live Caption icon if it does not appear automatically (this varies by phone brand — Samsung, Pixel, and others each place it slightly differently). A caption box appears on screen showing the other person\'s words as text in real time.',
      },
      {
        title: 'Adjust caption size and appearance',
        content: 'On both iPhone and Android, you can usually tap a small "Aa" or settings icon on the caption window itself to make the text larger, change the background color for better contrast, or switch to a bold font — helpful for anyone with low vision as well as hearing difficulty.',
      },
    ],
  },

  {
    slug: 'freeze-credit-all-three-bureaus',
    title: 'How to Freeze Your Credit at All Three Bureaus to Prevent Identity Theft',
    excerpt: 'A credit freeze is a free, powerful way to stop scammers from opening new accounts in your name. Here is how to freeze your credit at Equifax, Experian, and TransUnion.',
    category: 'financial-tech',
    tags: ['credit freeze', 'identity theft', 'fraud', 'equifax', 'experian', 'transunion'],
    readTime: '8 min',
    thumbnailEmoji: '🔒',
    publishedAt: '2026-07-26',
    lastVerifiedAt: '2026-07-26',
    difficulty: 'Beginner',
    body: `A credit freeze blocks anyone — including you — from opening a new credit card, loan, or other account in your name. That's because lenders cannot check your credit report while it is frozen. This makes it very difficult for identity thieves to use stolen personal information to open new accounts, even if they have your Social Security number.

Freezing your credit is free by federal law. It does not hurt your existing credit score, and it does not affect accounts you already have — you can still use your current credit cards normally. You do need to freeze it separately at all three major credit bureaus — Equifax, Experian, and TransUnion — because each one keeps its own separate report.

If you ever need to apply for new credit, or if a business needs to check your credit for a legitimate reason, like a new apartment or a phone plan, you can temporarily "thaw," or unfreeze, it. This takes just a few minutes online or by phone. You can refreeze it again afterward.

This guide walks through freezing your credit at all three bureaus, which takes about 15-20 minutes total.

(Sources: Federal Trade Commission — consumer.ftc.gov/articles/what-know-about-credit-freezes-and-fraud-alerts; Equifax, Experian, TransUnion official sites)`,
    steps: [
      {
        title: 'Gather your information',
        content: 'You will need your Social Security number, date of birth, current address, and a form of ID (driver\'s license number often helps speed things up). Have this ready before you start so you are not searching for it mid-process.',
      },
      {
        title: 'Freeze your credit at Equifax',
        content: 'Go to equifax.com/personal/credit-report-services and look for "Freeze/Lock your Equifax Credit Report." Create a free account or log in, then follow the prompts to place a freeze. You will be asked to create a PIN or password — write this down and keep it somewhere safe, since you will need it to unfreeze later.',
      },
      {
        title: 'Freeze your credit at Experian',
        content: 'Go to experian.com/freeze and select "Add a Security Freeze." Create an account, verify your identity by answering a few questions about your credit history, and confirm the freeze. Experian will give you a confirmation and PIN — save this too.',
      },
      {
        title: 'Freeze your credit at TransUnion',
        content: 'Go to transunion.com/credit-freeze and select "Freeze my TransUnion Credit Report." Create an account, verify your identity, and confirm. TransUnion also provides a confirmation you should save.',
        tip: 'Quick Tip: Keep all three PINs and confirmation numbers together in one place — a password manager, a locked document, or a written note in a secure location. You will need them to thaw your credit later.',
      },
      {
        title: 'Know how to temporarily thaw your credit when needed',
        content: 'If you are applying for a new credit card, loan, apartment, or phone plan, log back in to whichever bureau the business will check (they usually tell you, or you may need to thaw all three to be safe) and select "Temporarily lift freeze." You can choose a specific date range or thaw indefinitely, then refreeze when done.',
      },
      {
        title: 'Also consider freezing your minor grandchildren\'s credit if you are a guardian',
        content: 'Children\'s Social Security numbers are frequently stolen for identity theft precisely because nobody checks a child\'s credit report for years. Parents and legal guardians can freeze a minor\'s credit at all three bureaus using a similar process, which requires extra documentation like a birth certificate.',
      },
    ],
  },

  {
    slug: 'apple-check-in-safety-feature',
    title: 'How to Use Apple\'s "Check In" Feature to Let Family Know You Got Home Safe',
    excerpt: 'Check In automatically lets a chosen family member know when you arrive safely at your destination, and alerts them with your location if you do not.',
    category: 'safety-guides',
    tags: ['check in', 'safety', 'iphone', 'family', 'location sharing', 'apple'],
    readTime: '5 min',
    thumbnailEmoji: '📍',
    publishedAt: '2026-07-26',
    lastVerifiedAt: '2026-07-26',
    difficulty: 'Beginner',
    body: `Check In is a free, built-in iPhone feature (inside the Messages app) that automatically tells a family member or friend when you have arrived safely at a destination — a home, a doctor's appointment, a friend's house. If you do not arrive as expected, it can automatically share helpful information like your last known location and battery level with the person you chose, so they can check on you.

This is especially useful for a senior who drives alone, walks somewhere, or takes a trip, and for the family member who worries about them getting there safely. Unlike constant location sharing, Check In only shares your live location if something seems off — the rest of the time, it stays private.

Check In requires iOS 17 or later on both your iPhone and the family member's iPhone.

(Sources: Apple Support — support.apple.com/guide/iphone/check-in)`,
    steps: [
      {
        title: 'Open a conversation with the person you want to notify',
        content: 'Open the Messages app and open (or start) a text conversation with the family member or friend you want to let know when you arrive somewhere safely.',
      },
      {
        title: 'Tap the plus (+) button and select Check In',
        content: 'Tap the plus button next to the message text box, then tap "Check In." If this is your first time, the app will briefly explain how it works — tap through the introduction screens.',
      },
      {
        title: 'Confirm your destination and expected arrival',
        content: 'Check In will guess your destination based on your recent routes (like "Home"), or you can pick a different one. It shows an estimated arrival time based on your typical travel speed. Tap "Send" to start the Check In.',
        tip: 'Quick Tip: You can also manually set how long the Check In should last if you are not driving directly there — for example, if you are stopping at the store first.',
      },
      {
        title: 'What happens when you arrive',
        content: 'When you arrive at your destination, your phone recognizes this automatically and sends a message to the person letting them know you made it, with no action needed from you.',
      },
      {
        title: 'What happens if you do not arrive as expected',
        content: 'If you do not reach your destination in the expected time, your iPhone will first check in with you privately, asking if you need more time or if you are okay. If you do not respond, it automatically shares your current location, route, cell service level, and battery percentage with the person you chose — this information helps them know where to look for you or who to call.',
      },
      {
        title: 'Cancel a Check In early if you no longer need it',
        content: 'If your plans change, open the conversation, tap the active Check In banner, and tap "Stop." This ends the Check In without sending any alert.',
      },
    ],
  },

  {
    slug: 'amazon-subscribe-and-save-guide',
    title: 'How to Use Amazon Subscribe & Save to Get Discounts on Regular Purchases',
    excerpt: 'If you buy the same items on Amazon repeatedly — vitamins, coffee, pet food, paper towels — Subscribe & Save can knock 5-15% off the price automatically.',
    category: 'buying-guides',
    tags: ['amazon', 'subscribe and save', 'shopping', 'discounts', 'money saving'],
    readTime: '6 min',
    thumbnailEmoji: '📦',
    publishedAt: '2026-07-26',
    lastVerifiedAt: '2026-07-26',
    difficulty: 'Beginner',
    body: `Subscribe & Save is a free Amazon program that automatically reorders and ships items you use regularly, on a schedule you set, at a discount. It's usually 5% off, or 15% off if you get five or more Subscribe & Save items in the same month. There's no membership fee for the program itself, though Amazon Prime often adds free shipping on top.

This works best for things you buy the same way every time: vitamins, coffee, laundry detergent, pet food, paper towels, or printer ink. You're never charged more than the normal price. You can change the delivery schedule, skip a delivery, or cancel anytime with no penalty or fee.

This guide walks through setting up your first Subscribe & Save item and managing your subscriptions afterward.

(Sources: Amazon Customer Service — amazon.com/help)`,
    steps: [
      {
        title: 'Find an eligible product',
        content: 'Search for an item on Amazon that you buy repeatedly. On the product page, look for a box near the price that says "Subscribe & Save" with a discounted price shown, next to the regular "Buy Now" option. Not every product offers this — mostly household goods, groceries, and personal care items do.',
      },
      {
        title: 'Choose Subscribe & Save and set your delivery frequency',
        content: 'Select the "Subscribe & Save" option instead of a one-time purchase. Choose how often you want it delivered — options are usually every 1, 2, 3, or 6 months. Pick a schedule that roughly matches how long the item actually lasts you, so you do not build up extra unused stock.',
        tip: 'Quick Tip: Start with a shorter interval like monthly. You can always stretch it out later if items are arriving faster than you use them. It is much easier to lengthen the gap than to guess right the first time.',
      },
      {
        title: 'Complete checkout like a normal order',
        content: 'Confirm your payment method and delivery address just like any Amazon order. Your first delivery ships right away (or on the date you choose), and future deliveries repeat automatically on your set schedule.',
      },
      {
        title: 'Manage your subscriptions anytime',
        content: 'Go to amazon.com and click "Accounts & Lists," then "Memberships & Subscriptions," then "Subscribe & Save." Here you see every active subscription. You can change quantity, change frequency, skip the next delivery, or cancel any single item — none of these actions affect your other subscriptions.',
      },
      {
        title: 'Get the bigger discount by combining subscriptions',
        content: 'If you have five or more Subscribe & Save items scheduled to arrive in the same delivery month, Amazon automatically increases your discount from 5% to 15% on all of them for that month. Grouping a few regular purchases onto the same rough schedule can add up to real savings over a year.',
        warning: 'Watch your email for Amazon\'s reminder before each shipment. If an item is no longer needed, skip or cancel it before it ships — once it ships, it works like a normal order and follows Amazon\'s regular return policy.',
      },
    ],
  },
];
