// guides-batch-282 (recovered from main's original batch 138) — Auto-generated by creative-loop on 2026-05-05
// Topics: How to Print from Your Phone (No Computer Needed); How to Block and Silence Spam Calls on iPhone and Android

import type { Guide } from './guides';

export const guidesBatch282: Guide[] = [
  {
    slug: 'print-from-iphone-android-airprint',
    title: 'How to Print from Your Phone (No Computer Needed)',
    excerpt: 'You can print directly from any modern iPhone or Android phone to most Wi-Fi printers — no computer required. Here is how.',
    category: 'how-to',
    tags: ['print', 'airprint', 'iphone', 'android', 'wifi', 'seniors', 'printer'],
    readTime: '5 min',
    thumbnailEmoji: '📄',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Most home printers sold in the past several years can print directly from a phone over Wi-Fi — no computer needed. iPhones use a feature called AirPrint. Android phones use Google Cloud Print or a manufacturer app (HP Smart, Epson iPrint, Canon Print, Brother iPrint).

The setup is usually simple: as long as your phone and printer are on the same home Wi-Fi network, your phone can find the printer automatically. After the first time, printing takes about three taps.

If your printer is older than ~2018, it may not support AirPrint. In that case, the manufacturer app or a free service like Printer Pro can usually still get you printing. This guide focuses on the AirPrint and HP Smart paths since they cover the majority of home printers.

(Sources: Apple Support — AirPrint, support.apple.com/HT201311; HP Smart app, hp.com/go/mobileprinting)`,
    steps: [
      {
        title: 'Make sure your printer is on and connected to Wi-Fi',
        content: 'Turn on your printer. Look at its small screen or status lights — it should show that it is connected to your home Wi-Fi network. If not, follow the printer\'s setup card or call your printer manufacturer\'s support line. The printer must be on the same Wi-Fi network as your phone.',
      },
      {
        title: 'On iPhone: open the document, photo, or page you want to print',
        content: 'Open whatever you want to print — a photo in Photos, an email in Mail, a recipe in Safari. Tap the Share button (a square with an arrow pointing up). Scroll down through the menu and tap Print.',
      },
      {
        title: 'iPhone: pick your printer and settings',
        content: 'On the Print Options screen, tap "Select Printer." Your iPhone scans the Wi-Fi network and shows all available printers. Tap your printer. You can choose how many copies, page range, color or black-and-white, and paper size. Tap Print at the top right.',
        tip: 'Quick Tip: After you print to a printer once, the iPhone remembers it. Future prints default to the same printer automatically.',
      },
      {
        title: 'On Android: install the manufacturer app',
        content: 'Most Android phones can print without an app, but the manufacturer app gives you more options. For HP printers, install HP Smart from Google Play. For Epson, install Epson iPrint. For Canon, install Canon Print. For Brother, install Brother iPrint&Scan. Open the app and follow the setup — it finds your printer automatically.',
      },
      {
        title: 'Android: print from any app',
        content: 'In any app, tap the share or menu button and choose Print. If you do not see Print, tap "Print" inside the manufacturer app instead — most have a "Print Anything" or "Documents" section where you can browse to the file you want.',
      },
      {
        title: 'Troubleshoot if the printer does not appear',
        content: 'If your phone cannot find the printer, check that both are on the same Wi-Fi network (look at your phone\'s Wi-Fi settings — they should show the same network name). Restart the printer (turn off, wait 30 seconds, turn on). Restart your phone. If it still fails, call your printer manufacturer support — most offer free phone help.',
      },
    ],
  },

  {
    slug: 'reduce-spam-calls-iphone-android',
    title: 'How to Block and Silence Spam Calls on iPhone and Android',
    excerpt: 'Spam calls are exhausting. iPhone and Android have free, built-in tools that filter most of them out. Here is how to turn them on.',
    category: 'safety-guides',
    tags: ['spam', 'phone-calls', 'iphone', 'android', 'block', 'safety', 'seniors'],
    readTime: '5 min',
    thumbnailEmoji: '🛡️',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Most Americans now receive several spam calls per day — fake car warranty offers, fake Medicare offers, fake IRS calls, and worse. Both iPhone and Android have built-in features that send unknown callers to voicemail automatically, label suspected spam in red, and let you block specific numbers. Used together, these tools can cut spam call volume by 80 to 90 percent.

This guide covers the four free tools that work for nearly everyone: Silence Unknown Callers (iPhone), Caller ID warnings (both phones), Do Not Disturb / Focus Mode, and your carrier's free spam-blocking service (which works for both iPhone and Android).

You do not need a paid app. Apps like RoboKiller and Hiya have free tiers, but the built-in tools are usually enough.

(Sources: FTC — Stop unwanted calls, consumer.ftc.gov/articles/how-stop-unwanted-calls; AT&T ActiveArmor, att.com/activearmor; Verizon Call Filter, verizon.com/solutions-and-services/call-filter)`,
    steps: [
      {
        title: 'On iPhone: turn on Silence Unknown Callers',
        content: 'On your iPhone, open Settings → Phone → Silence Unknown Callers. Turn the switch on (green). Now any caller whose number is not in your contacts, recent outgoing calls, or Siri suggestions goes straight to voicemail. Real callers can still leave a message; spam callers usually do not.',
        tip: 'Quick Tip: This may also silence legitimate calls from doctors, pharmacies, or delivery drivers. Either add their numbers to your contacts in advance, or check your voicemail regularly for any messages.',
      },
      {
        title: 'On Android: turn on Caller ID and Spam Protection',
        content: 'On most Android phones with the Google Phone app, open the Phone app → tap the three-dot menu → Settings → Caller ID and spam → turn on "See caller and spam ID" and "Filter spam calls." Suspected spam calls now appear in red and are sent to voicemail automatically.',
      },
      {
        title: 'Sign up for your carrier\'s free spam blocking',
        content: 'AT&T offers ActiveArmor (free at att.com/activearmor). Verizon offers Call Filter (free at verizon.com/call-filter). T-Mobile offers Scam Shield (free at t-mobile.com/scamshield). Each is free at the basic tier and uses carrier network-level data to block known scam numbers before they ring your phone. Sign up through the carrier\'s app or website.',
      },
      {
        title: 'Block specific recurring callers',
        content: 'When a spam call gets through, you can block that exact number so it never rings again. On iPhone, tap the red "i" next to the call in your Recents list, scroll to the bottom, and tap "Block this Caller." On Android, long-press the number in the call log and tap Block.',
      },
      {
        title: 'Add yourself to the National Do Not Call Registry',
        content: 'Visit donotcall.gov and enter your phone number. Legitimate telemarketers are required to stop calling within 31 days. This does not stop scammers — they ignore the law — but it cuts the volume from real telemarketers significantly. The registration is permanent and free.',
      },
      {
        title: 'Never call back or press buttons during a spam call',
        content: 'If a spam call gets through and you answer, hang up immediately. Do not press buttons even if the message says "press 9 to be removed." Pressing anything confirms your number is active and triggers more calls. Hang up. Likewise, never call back a missed call from an unfamiliar number — many spam scams rely on call-back charges.',
        warning: 'Some scams imitate familiar local area codes ("neighbor spoofing"). If you do not recognize the number, let it go to voicemail.',
      },
    ],
  },
];
