// guides-batch-286 (recovered from main's original batch 142) — Auto-generated by creative-loop on 2026-05-05
// Topics: Find the Name of Any Song You Hear with Shazam (Built Into iPhone)

import type { Guide } from './guides';

export const guidesBatch286: Guide[] = [
  {
    slug: 'use-shazam-iphone-name-that-song',
    title: 'Find the Name of Any Song You Hear with Shazam (Built Into iPhone)',
    excerpt: 'Hear a song on the radio or in a store and want to know what it is? Shazam identifies any song in seconds — and is built into iPhone.',
    category: 'entertainment',
    tags: ['shazam', 'music', 'iphone', 'song-id', 'apple', 'seniors'],
    readTime: '3 min',
    thumbnailEmoji: '🎵',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Shazam is a free service that identifies songs by listening to them. You hear a song on the car radio, in a restaurant, or in a store, and Shazam tells you the name of the song, the artist, and where to find it. It works in seconds.

Apple owns Shazam, and starting with iOS 15, Shazam is built directly into iPhone — you do not need to download an app. You can ask Siri "What song is this?" or add a Shazam button to Control Center for one-tap identification.

There is also a free Shazam app available on iPhone and Android with extra features like saved history of every song you have identified.

(Sources: Apple Support — Identify music with Shazam, support.apple.com/HT212725)`,
    steps: [
      {
        title: 'Ask Siri "What song is this?"',
        content: 'When you hear a song, hold down the side button on your iPhone (or say "Hey Siri") and ask "What song is this?" Siri listens for a few seconds and answers with the song name and artist. You can then tap "Open in Music" or "Open in Spotify" to play the full song or save it.',
      },
      {
        title: 'Add Shazam to Control Center for one-tap identification',
        content: 'For faster access, add a Shazam button to Control Center. Open Settings → Control Center. Scroll down to "Music Recognition" and tap the green + to add it. Now swipe down from the top right corner of any screen to access Control Center, and tap the Shazam icon to identify any song playing nearby.',
        tip: 'Quick Tip: This works even when your iPhone is connected to Bluetooth headphones or playing music itself — Shazam can pick up sounds from the room while music plays in your ears.',
      },
      {
        title: 'See your Shazam history',
        content: 'Every song you identify is saved automatically to a list. To see it, swipe down from Control Center and tap-and-hold the Shazam icon. A list of every song you have ever Shazam\'d appears, with dates. Tap any song to play it or save it to a playlist.',
      },
      {
        title: 'Install the Shazam app for more features',
        content: 'For features like a desktop widget, watch app, and offline mode, install the free Shazam app from the App Store. The app version also lets you Shazam songs that are saved as videos in your photo library — useful when you forgot to identify a song that was playing in a video clip.',
      },
      {
        title: 'Use Shazam to find live music or shows',
        content: 'After identifying a song, tap the artist name in the result. The Shazam app shows you upcoming concerts in your area, music videos, and similar songs. This makes Shazam a small but powerful tool for discovering new music based on what you actually like, not what an algorithm guesses.',
      },
    ],
  },
];
