// guides-batch-285 (recovered from main's original batch 141) — Auto-generated by creative-loop on 2026-05-05
// Topics: Use Google Translate to Translate Anything with Your Phone Camera; Make Sense of iCloud Storage (and Stop Getting "Storage Full" Warnings)

import type { Guide } from './guides';

export const guidesBatch285: Guide[] = [
  {
    slug: 'use-google-translate-camera-real-time',
    title: 'Use Google Translate to Translate Anything with Your Phone Camera',
    excerpt: 'Point your phone at a foreign menu, sign, or label and Google Translate shows you the English translation in real time. Here is how.',
    category: 'app-guides',
    tags: ['translate', 'google-translate', 'travel', 'camera', 'language', 'seniors'],
    readTime: '4 min',
    thumbnailEmoji: '📄',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Google Translate is a free app that translates between over 100 languages. The most useful feature for travelers and people who deal with foreign-language documents is the camera — point your phone at any text, and Google Translate replaces the words on screen with English in real time.

You can also speak into the app and have it translate aloud (useful for conversations with someone who speaks a different language), translate handwritten notes by drawing on the screen, or download languages for offline use (so it works without internet, perfect for international travel).

The camera translation works for menus in restaurants, signs in airports, prescription labels in foreign pharmacies, ingredient lists, road signs, and product packaging. It is one of the most genuinely useful free apps available.

(Sources: Google Translate Help, support.google.com/translate)`,
    steps: [
      {
        title: 'Install Google Translate',
        content: 'Open the App Store (iPhone) or Google Play (Android) and search for "Google Translate." Install the app — look for the official Google logo. Open it and pick your two languages (one you speak, one you want to translate to or from).',
      },
      {
        title: 'Tap the camera icon',
        content: 'On the Google Translate home screen, tap the Camera icon. Allow Google Translate to use your camera when prompted. Point the camera at any text — a foreign menu, a road sign, a label.',
      },
      {
        title: 'Watch the text translate live',
        content: 'The app overlays the English translation directly on top of the foreign text in real time. Hold the camera steady and the words appear right where the original text was. This works for menus, signs, ingredients, prescription labels, instruction sheets — anything with printed text.',
        tip: 'Quick Tip: For a clearer image, tap the shutter button to take a picture. Then tap and drag your finger across the words you want translated more carefully. You can copy the translated text or have the iPhone read it aloud.',
      },
      {
        title: 'Use Conversation mode for two-way talking',
        content: 'Tap "Conversation" on the home screen. Tap the microphone for your language and speak. Google Translate shows the translation in the other language, then plays it aloud through the speaker. The other person can speak back into the same app and you hear the English. Useful for talking to a non-English-speaking neighbor, doctor visit interpreter, or shopkeeper while traveling.',
      },
      {
        title: 'Download languages for offline use',
        content: 'Before traveling internationally, download your destination\'s language so the app works without Wi-Fi or data. On the home screen, tap your profile icon → "Downloaded languages." Tap the download arrow next to languages you want offline. Each takes about 50 MB of phone storage.',
      },
      {
        title: 'Save translations you use often',
        content: 'After translating something, tap the star icon to save it. Saved translations appear under "Phrasebook" — useful for common medical phrases, food allergies, or directions you might need repeatedly while traveling.',
      },
    ],
  },

  {
    slug: 'organize-icloud-storage-iphone-backup',
    title: 'Make Sense of iCloud Storage (and Stop Getting "Storage Full" Warnings)',
    excerpt: 'Apple\'s "iCloud Storage Full" warning is one of the most confusing notifications. Here is what it actually means and how to fix it.',
    category: 'phone-guides',
    tags: ['icloud', 'storage', 'backup', 'iphone', 'apple', 'seniors'],
    readTime: '7 min',
    thumbnailEmoji: '📱',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Apple gives every Apple ID 5 GB of free iCloud storage. iCloud is where your iPhone backs up — photos, messages, app data — so you can restore everything if you lose your phone. 5 GB is small. Most people fill it within a year and start receiving "iCloud Storage Full" warnings, which then prevent backups, prevent new photos from syncing, and clutter the screen with reminders.

You have three options: free up space by deleting old backups or photos, ignore the warnings (not recommended — your phone is no longer being backed up), or upgrade to iCloud+ for $0.99 per month for 50 GB or $2.99 per month for 200 GB. The 50 GB plan is enough for most people.

This guide explains what is using your iCloud space, how to clean it up, and whether to upgrade.

(Sources: Apple Support — iCloud storage, support.apple.com/HT201318; iCloud+ pricing, apple.com/icloud)`,
    steps: [
      {
        title: 'Check what is taking up space',
        content: 'Open Settings on your iPhone. Tap your name at the top. Tap iCloud. You see a colored bar showing what is using your iCloud space — usually Photos and Backups are the biggest. Below the bar is a "Manage Storage" or "Manage Account Storage" link. Tap it.',
      },
      {
        title: 'Delete old device backups',
        content: 'In Manage Storage, tap "Backups." You see backups of every Apple device you have ever used with your Apple ID — including old iPads or iPhones you no longer have. Tap any backup for an old device, scroll down, and tap "Delete Backup." This often frees several GB instantly.',
        tip: 'Quick Tip: Do NOT delete the backup of your current iPhone. Always look at the device name carefully. The current iPhone is at the top of the list.',
      },
      {
        title: 'Move photos to Google Photos for free unlimited backup',
        content: 'Photos are usually the biggest user of iCloud space. A free alternative: install Google Photos (15 GB free) or use both. Once Google Photos has copies of your photos, you can safely delete them from iCloud. Many people use both — Apple Photos for instant access, Google Photos as a free unlimited backup.',
      },
      {
        title: 'Turn off iCloud backups for apps you do not need',
        content: 'In Manage Storage, scroll through the list of apps. Each shows how much iCloud space it uses for backups. For apps you do not care about restoring (like a casual game), tap the app, then "Turn Off and Delete from iCloud." This removes that app\'s data from iCloud and frees space.',
        warning: 'Do not turn off backup for important apps like Mail, Calendar, Contacts, or anything you would miss if your phone broke. The whole point of iCloud is to restore those.',
      },
      {
        title: 'Decide whether to upgrade',
        content: 'If your iCloud is full and you would rather not delete things, the 50 GB iCloud+ plan is $0.99/month and is plenty for most people. The 200 GB plan ($2.99/month) is enough to share storage across a whole family and includes Apple\'s privacy features. To upgrade, in Manage Storage, tap "Upgrade" or "Change Storage Plan." Cancel any time.',
      },
      {
        title: 'Confirm your phone is being backed up',
        content: 'After cleaning up or upgrading, confirm backups are working. Settings → your name → iCloud → iCloud Backup. The "Last successful backup" date should be within the past few days. If not, tap "Back Up Now" to manually trigger one. From now on, the iPhone backs up automatically when on Wi-Fi and charging overnight.',
      },
    ],
  },
];
