// guides-batch-129 — Auto-generated by creative-loop on 2026-05-05
// Topics: How to Recognize the Grandparent Scam (and What to Say if You Get the Call); Use Amazon Pharmacy to Get Prescriptions Delivered (Often Cheaper than Walgreens)

import type { Guide } from './guides';

export const guidesBatch129: Guide[] = [
  {
    slug: 'recognize-grandparent-scam-2026',
    title: 'How to Recognize the Grandparent Scam (and What to Say if You Get the Call)',
    excerpt: 'A frantic call from someone claiming to be your grandchild in trouble is almost always a scam. Here is exactly how to tell — and what to say.',
    category: 'safety-guides',
    tags: ['scam', 'grandparent-scam', 'phone-scam', 'safety', 'seniors', 'family', 'fraud'],
    readTime: '6 min',
    thumbnailEmoji: '🛡️',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `The grandparent scam is one of the most common and emotionally damaging scams targeting seniors in the United States. The Federal Trade Commission tracks tens of thousands of these calls every year, and average losses are now over $9,000 per victim.

The scam usually goes like this: An elderly person receives a phone call. A young voice (sometimes synthesized to sound like their grandchild) cries "Grandma, it's me — I'm in trouble!" An "officer" or "lawyer" then takes the phone and explains that the grandchild has been arrested, in a car accident, or kidnapped, and needs immediate bail or hospital payment. The caller asks for cash, gift cards, wire transfers, or cryptocurrency, and insists the grandparent not call other family members.

Every part of this script is engineered to bypass critical thinking. The crying voice triggers protective instincts. The urgency prevents you from pausing to verify. The instruction not to call others isolates you. AI voice cloning has made these calls dramatically more convincing in 2025 and 2026 — scammers can pull a few seconds of audio from a grandchild's social media and produce a near-perfect voice clone.

The good news: a single phrase will reveal the scam every time. This guide walks through how the scam works, what to say to confirm it, and what to do if you have already sent money.

(Sources: FTC Consumer Information — Family emergency scams, consumer.ftc.gov; AARP Fraud Watch Network, aarp.org/money/scams-fraud; FBI Internet Crime Complaint Center, ic3.gov)`,
    steps: [
      {
        title: 'Pause before reacting to the emotion',
        content: 'When someone calls in tears claiming to be a family member, the natural reaction is to help immediately. Scammers count on this. Take a breath. Tell the caller "Wait one moment, please" — and put the phone down for ten seconds. A real grandchild in real trouble can wait ten seconds. A scammer often hangs up.',
      },
      {
        title: 'Ask a question only your real grandchild could answer',
        content: 'Pick something a stranger could not look up online. Not "what is your dog\'s name" (often on Facebook). Try things like "what was the name of the camp you went to in fourth grade" or "what did Grandpa always call you." If the caller hesitates, makes excuses about being too upset to remember, or tries to change the subject — it is a scam. Hang up.',
        tip: 'Quick Tip: Set up a family password word in advance — a word only your immediate family knows. If anyone calls claiming to be a family member in trouble, ask for the family password.',
      },
      {
        title: 'Hang up and call the grandchild back directly',
        content: 'Real or not, hang up. Then call your grandchild directly using the number you already have for them. If they pick up calmly, you know the call was a scam. If they do not answer, call your child (their parent) to verify. This step alone defeats the grandparent scam in nearly every case — scammers cannot fake a real phone number.',
        warning: 'Do NOT use the callback number the scammer gives you. They will route you to an accomplice posing as a hospital, jail, or police department.',
      },
      {
        title: 'Recognize the payment requests that signal a scam',
        content: 'Real bail bondsmen, hospitals, and police departments never ask for payment by gift cards, cryptocurrency, wire transfers (Western Union or MoneyGram), or cash sent by courier. If anyone on a phone call asks for any of these, it is a scam. No exceptions. Hospitals send bills by mail. Police do not collect bail by phone.',
      },
      {
        title: 'If you already sent money, act fast',
        content: 'Wire transfers can sometimes be reversed if reported within hours — call your bank or wire service immediately. Gift card balances can occasionally be frozen if the codes have not been redeemed — call the card issuer (Apple, Google Play, Amazon, etc.) right away. Cryptocurrency transactions are usually unrecoverable, but reporting helps law enforcement track patterns. File a report at reportfraud.ftc.gov and at ic3.gov.',
      },
      {
        title: 'Share what you learned with friends',
        content: 'Talking about scams openly is the best protection. Many seniors feel ashamed to discuss being targeted, which lets scammers operate freely. Tell your friends what to listen for — and let them know if they ever get one of these calls, you will not judge them for asking your advice. Communities that talk about scams have lower victimization rates.',
      },
    ],
  },

  {
    slug: 'set-up-amazon-prime-delivery-prescriptions',
    title: 'Use Amazon Pharmacy to Get Prescriptions Delivered (Often Cheaper than Walgreens)',
    excerpt: 'Amazon Pharmacy offers prescription delivery, often at lower prices than CVS or Walgreens — even without insurance. Here is how to get started.',
    category: 'health-tech',
    tags: ['amazon-pharmacy', 'prescriptions', 'medications', 'delivery', 'seniors', 'health'],
    readTime: '6 min',
    thumbnailEmoji: '🏥',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Amazon Pharmacy is a fully licensed online pharmacy that delivers prescription medications to your door, often at prices significantly lower than CVS, Walgreens, or Walmart. It accepts most insurance plans (including Medicare Part D) and offers a separate discount program called RxPass for Prime members that includes many common generics for $5 per month total.

Switching to Amazon Pharmacy does not mean giving up your current pharmacy — you can keep one prescription at Walgreens and have another at Amazon. There is no commitment. If a delivery does not arrive on time, Amazon's customer service handles it like any other Amazon order.

The main considerations: delivery takes 3 to 5 days, so this works for ongoing medications you take daily, not for urgent prescriptions like antibiotics. And while Amazon's prices are often lower, comparing prices on GoodRx is still worthwhile for some medications.

This guide walks through setting up Amazon Pharmacy, transferring an existing prescription, and using insurance or the RxPass program.

(Sources: Amazon Pharmacy, pharmacy.amazon.com; RxPass details, amazon.com/rxpass; GoodRx price comparison, goodrx.com)`,
    steps: [
      {
        title: 'Sign in at pharmacy.amazon.com',
        content: 'You can use Amazon Pharmacy with any Amazon account — Prime membership is not required for the main pharmacy (only for the RxPass discount program). Go to pharmacy.amazon.com and sign in with the same email and password you use for amazon.com.',
      },
      {
        title: 'Add your insurance information',
        content: 'Click "Add insurance" and enter the details from your insurance card — Member ID, Group Number, BIN, and PCN. All four are printed on the card. If you have Medicare Part D, the card from your Part D plan (not the red, white, and blue Medicare card) is the right one to enter.',
        tip: 'Quick Tip: If you do not have insurance, skip this step. Amazon Pharmacy will show you cash prices and let you compare them to discount programs like SingleCare or GoodRx coupons, which Amazon often accepts.',
      },
      {
        title: 'Transfer a prescription from your current pharmacy',
        content: 'On the Amazon Pharmacy home page, click "Transfer a prescription." Type the medication name. Amazon walks you through providing your current pharmacy\'s name, your prescription number (from the bottle label), and your prescriber\'s name. Amazon contacts your old pharmacy and pulls the prescription over — usually within 1 business day. You can keep filling at your old pharmacy until the transfer is complete.',
      },
      {
        title: 'Compare prices across plans',
        content: 'Amazon Pharmacy automatically shows you three prices side-by-side: your insurance price, the cash price (no insurance), and the Prime member price. Pick whichever is cheapest. For some medications, paying cash is actually less than the insurance copay — Amazon shows you both so you can choose.',
      },
      {
        title: 'Schedule delivery',
        content: 'Standard shipping is free for Amazon Pharmacy. For Prime members, free 2-day shipping is included. Pick a delivery date and address. The package arrives in plain packaging without anything visible from outside about the contents. Refrigerated medications arrive in insulated boxes with cold packs.',
        warning: 'For controlled medications (like ADHD or pain medications), an adult must sign for the package. Plan to be home or have someone available.',
      },
      {
        title: 'Consider RxPass if you take multiple generics',
        content: 'If you take 2 or more generic medications regularly, Prime members can subscribe to RxPass for $5 per month. RxPass covers about 60 common generic medications — including blood pressure, cholesterol, diabetes, and depression medications. There is no per-prescription copay; the $5 is your only cost. Check the RxPass medication list at amazon.com/rxpass to see if your prescriptions are covered.',
      },
    ],
  },
];
