// guides-batch-332 — Auto-generated by 90-day sprint task on 2026-08-04
// Topics: AI voice cloning "grandparent scam"; Medicare 2027 Open Enrollment prep;
// iOS 26 Liquid Glass design changes; password manager basics; back-to-school
// tech scams targeting grandparents buying for grandkids

import type { Guide } from './guides';

export const guidesBatch332: Guide[] = [
  {
    slug: 'ai-voice-cloning-grandparent-scam',
    title: 'The New "Grandparent Scam": How AI Voice Cloning Fools Families',
    excerpt: 'Scammers now clone a real family member\'s voice from just a few seconds of audio. Here is how the scam works and how to protect yourself.',
    category: 'safety-guides',
    tags: ['ai scam', 'voice cloning', 'grandparent scam', 'imposter scam', 'deepfake', 'fraud'],
    readTime: '6 min',
    thumbnailEmoji: '📞',
    publishedAt: '2026-08-04',
    lastVerifiedAt: '2026-08-04',
    difficulty: 'Beginner',
    body: `The "grandparent scam" is not new — a caller pretends to be a grandchild in trouble and begs for money to be sent right away. What is new is how convincing it has become. Scammers now use AI voice-cloning tools that need only a few seconds of a person's real voice — often pulled from a public social media video, a voicemail greeting, or a video call — to generate a fake recording that sounds remarkably like them, including tone of voice and manner of speaking.

The call typically follows a script: a panicked-sounding "grandchild" says they have been in a car accident, arrested, or are stuck in another country, and a second person — playing a lawyer, bail bondsman, or police officer — gets on the line to explain that money is needed immediately, usually through gift cards, a wire transfer, cryptocurrency, or cash handed to a courier. The Federal Trade Commission reports that imposter scams like this are now the most reported type of fraud complaint, with family-emergency scams averaging around $11,000 in losses per victim, frequently in a single call.

The single most reliable defense does not depend on spotting a fake voice — even a very convincing one. It is verification through a second channel. Hang up, and call the family member back directly using the phone number you already have saved for them, not a number the caller gives you. If you cannot reach them, call another family member to check. A real emergency will withstand a few minutes of you confirming it; a scam depends on you not taking that time.

(Sources: Federal Trade Commission consumer alerts — consumer.ftc.gov; AARP Fraud Watch Network — aarp.org)`,
    steps: [
      {
        title: 'Hang up and call back on a number you already trust',
        content: 'If you get an urgent call from someone claiming to be a grandchild or family member asking for money, hang up. Call that person back on the phone number already saved in your contacts — not a number the caller provided. If they do not answer, call another relative to check on them before doing anything else.',
      },
      {
        title: 'Agree on a family "safe word"',
        content: 'Pick a word or short phrase with your close family that only you would know, to be used if anyone ever calls in a real emergency asking for money. If a caller cannot provide it, treat the call as a scam.',
        tip: 'Quick Tip: Choose something unrelated to information posted online or on social media, since scammers research public posts before calling.',
      },
      {
        title: 'Slow down — urgency itself is the warning sign',
        content: 'Scammers deliberately create panic and pressure you to act before you can think clearly or call anyone else. A real emergency almost never requires you to send money within minutes, in gift cards, or without telling any other family member. Treat extreme urgency as a red flag, not proof of a real crisis.',
      },
      {
        title: 'Never pay with gift cards, crypto, or a wire transfer for an "emergency"',
        content: 'No legitimate court, bail bondsman, hospital, or law enforcement agency asks for payment in gift cards or cryptocurrency. If a caller requests either, it is a scam, regardless of how believable the voice sounds.',
        warning: 'Once money is sent by gift card, wire transfer, or cryptocurrency, it is nearly impossible to get back. Verify before you send, not after.',
      },
      {
        title: 'Report the call',
        content: 'Report the scam attempt to the FTC at reportfraud.ftc.gov, and to your local police non-emergency line. If money was sent, contact the gift card company, wire service, or bank immediately — some have limited windows to reverse a transfer.',
      },
    ],
  },

  {
    slug: 'medicare-2027-open-enrollment-prep-guide',
    title: 'Medicare Open Enrollment 2027: How to Get Ready Before October',
    excerpt: 'Medicare Open Enrollment for 2027 coverage runs October 15 to December 7, 2026. Here is what to review now so you are not rushed in the fall.',
    category: 'government-civic',
    tags: ['medicare', 'open enrollment', 'health insurance', 'medicare advantage', 'part d', 'retirement'],
    readTime: '7 min',
    thumbnailEmoji: '🏥',
    publishedAt: '2026-08-04',
    lastVerifiedAt: '2026-08-04',
    difficulty: 'Beginner',
    body: `Medicare's Fall Open Enrollment Period — officially called the Annual Enrollment Period — runs from October 15 to December 7, 2026. Changes you make during this window take effect January 1, 2027. Anyone with Medicare can use this period to switch between Original Medicare and a Medicare Advantage plan, move from one Medicare Advantage plan to another, or join, switch, or drop a Part D prescription drug plan.

Many people wait until October to think about this at all, then feel rushed trying to compare plans in the seven-and-a-half-week window. A little preparation in August and September makes the fall period much less stressful, and it matters more than it might seem: Medicare plans can change their costs, covered drugs, and provider networks every single year, even if you take no action. A drug that was covered at a low cost this year could move to a more expensive tier next year, and a doctor's office that was in-network could drop out of your plan's network — both without you doing anything.

If you are happy with your current plan and it is not changing in ways that affect you, you do not have to do anything during Open Enrollment — your coverage will simply continue. But it is worth checking the details every year rather than assuming nothing changed.

(Sources: Medicare.gov — medicare.gov/health-drug-plans/open-enrollment; Centers for Medicare & Medicaid Services — cms.gov)`,
    steps: [
      {
        title: 'Watch for your "Annual Notice of Change" letter in September',
        content: 'Medicare plans are required to mail current members a notice explaining what is changing for the coming year — costs, covered drugs, and network changes. It typically arrives by late September. Read it even if you plan to keep your current plan.',
      },
      {
        title: 'List your current medications and doctors',
        content: 'Write down every prescription you take regularly and the doctors or specialists you see. You will need this list to check whether a plan still covers your medications at a reasonable cost and whether your providers remain in-network for 2027.',
      },
      {
        title: 'Use the Medicare Plan Finder to compare',
        content: 'Starting October 1, go to medicare.gov/plan-compare and enter your medications and zip code to see cost estimates for available plans in your area for the coming year. This tool is free and run directly by Medicare — not an insurance company.',
        tip: 'Quick Tip: If you would rather not compare plans online yourself, call 1-800-MEDICARE (1-800-633-4227) or your State Health Insurance Assistance Program (SHIP) for free, unbiased help — they do not sell insurance.',
      },
      {
        title: 'Make your decision by December 7',
        content: 'Any changes must be submitted by December 7, 2026, to take effect January 1, 2027. If you miss the deadline, you generally stay on your current plan until the next Open Enrollment period, roughly one year later.',
      },
      {
        title: 'Be alert for Open Enrollment scams',
        content: 'Every fall, scammers place calls or send mailers pretending to be from Medicare, pressuring people to "confirm" their Medicare number or bank details to keep coverage. Medicare will never call you uninvited asking for your Medicare number or payment information — hang up and call 1-800-MEDICARE directly if you are unsure.',
        warning: 'Never give your Medicare number, Social Security number, or bank information to anyone who calls you first claiming to represent Medicare.',
      },
    ],
  },

  {
    slug: 'ios-26-liquid-glass-design-what-changed',
    title: 'iOS 26 Looks Different: What Changed and How to Find Familiar Settings',
    excerpt: 'iOS 26 introduced a new "Liquid Glass" look with more see-through buttons and menus. Here is what changed and how to find things that moved.',
    category: 'phone-guides',
    tags: ['iphone', 'ios 26', 'liquid glass', 'apple', 'update', 'iphone settings'],
    readTime: '6 min',
    thumbnailEmoji: '📱',
    publishedAt: '2026-08-04',
    lastVerifiedAt: '2026-08-04',
    difficulty: 'Beginner',
    body: `If your iPhone updated to iOS 26 and suddenly looks different — buttons appear more see-through, menus have a glassy, layered look, and some icons shifted position — that is expected. Apple calls this new look "Liquid Glass," and it is the biggest visual redesign of the iPhone's software since iOS 7 was released back in 2013. The buttons, sliders, and navigation bars now appear translucent and can shift slightly depending on what is behind them, similar to looking through frosted glass.

This is a visual change, not a change to what your iPhone can do. Every app and setting you used before is still there — some icons and menu items simply moved to new locations or look different, which can be disorienting at first, especially if you have used the same layout for years.

If the new see-through look is hard to read or feels too busy, Apple included an accessibility option to reduce the transparency effect, making buttons and text solid and easier to read. This does not undo the redesign, but it removes the part most people find hardest to see clearly.

Apple has continued releasing smaller updates through the iOS 26.x series (iOS 26.6 as of late July 2026) that fix bugs and improve battery life without changing the overall design further.

(Sources: Apple Support — support.apple.com/en-us/123075; Apple Newsroom)`,
    steps: [
      {
        title: 'Make text and buttons easier to read',
        content: 'Go to Settings → Accessibility → Display & Text Size, and turn on "Reduce Transparency." This makes buttons, menus, and backgrounds more solid, which many people find easier to read than the default see-through look.',
      },
      {
        title: 'Turn on "Increase Contrast" if buttons are hard to tell apart',
        content: 'In the same Settings → Accessibility → Display & Text Size menu, turn on "Increase Contrast" to add visible borders around buttons and controls, making it clearer what is tappable.',
        tip: 'Quick Tip: These two settings can be combined for the most solid, readable look if the new glass design feels hard to use.',
      },
      {
        title: 'Find a moved setting or app',
        content: 'If you cannot find something that used to be in a familiar place, swipe down from the middle of any Home Screen and type what you are looking for into Spotlight Search — this finds settings, apps, and contacts by name even if the menu location changed.',
      },
      {
        title: 'Check that your iPhone is eligible before assuming a problem',
        content: 'iOS 26 works on iPhone 11 and newer. If your iPhone did not receive the update, it may not be supported — that is not a malfunction. Check your model under Settings → General → About.',
      },
      {
        title: 'Keep updating for security, even if you skip new looks',
        content: 'Smaller point updates like iOS 26.6 mostly contain security fixes and bug patches, not new redesigns. It is safe and recommended to install these — go to Settings → General → Software Update to check.',
      },
    ],
  },

  {
    slug: 'password-manager-basics-for-beginners',
    title: 'What Is a Password Manager, and Do You Actually Need One?',
    excerpt: 'A password manager remembers strong, unique passwords for every account so you do not have to. Here is what one does and how to start using it.',
    category: 'online-privacy',
    tags: ['password manager', 'passwords', 'online security', 'account safety', '2fa'],
    readTime: '6 min',
    thumbnailEmoji: '🔑',
    publishedAt: '2026-08-04',
    lastVerifiedAt: '2026-08-04',
    difficulty: 'Beginner',
    body: `A password manager is a program that creates, stores, and automatically fills in passwords for your online accounts, so you only need to remember one strong "master" password to unlock it. It solves a real problem: using the same simple password everywhere is convenient, but if just one of those sites is ever hacked, criminals try that same password on your email, bank, and other accounts — a technique called "credential stuffing" that succeeds far more often than people expect.

A password manager instead creates a long, random, unique password for every single account, so a breach at one company cannot be used to break into your others. It also fills those passwords in automatically on websites and apps, which is often faster than typing them yourself and avoids the temptation to write passwords on paper or reuse the same one out of frustration.

You likely already have a free password manager built into your phone or browser. iPhones have "Passwords" built into Settings, using iCloud Keychain to sync across your Apple devices. Android phones and Chrome have Google Password Manager built in. Both are free, reasonably secure, and a significant improvement over reusing passwords — no extra app required to get started. Dedicated apps like 1Password or Bitwarden offer more features, such as easier use across different device brands, for a low monthly fee (or free, in Bitwarden's case, for individual use).

(Sources: FTC consumer guidance on passwords — consumer.ftc.gov; Cybersecurity and Infrastructure Security Agency — cisa.gov)`,
    steps: [
      {
        title: 'Check the password manager you already have',
        content: 'On an iPhone, go to Settings → Passwords to see saved logins and generate new ones. On an Android phone, open Chrome, tap the three dots menu → Settings → Password Manager. Both are free and already installed.',
      },
      {
        title: 'Turn on autofill',
        content: 'On iPhone: Settings → Passwords → Password Options → turn on "AutoFill Passwords." On Android: within Google Password Manager settings, turn on "Auto Sign-in." This lets your phone fill in saved passwords automatically when you log into an app or website.',
      },
      {
        title: 'Let it generate strong passwords for new accounts',
        content: 'When creating a new account or changing a password, look for a suggested strong password offered by your phone or browser (often shown automatically in the password field) and use it instead of typing your own. Your phone remembers it for you.',
        tip: 'Quick Tip: Start with your email and banking passwords first — these protect the most important accounts if something else gets breached.',
      },
      {
        title: 'Set a strong master password or use your fingerprint/face',
        content: 'Most password managers unlock using your phone\'s existing Face ID, fingerprint, or passcode, rather than a separate password to remember. Make sure your phone\'s screen lock itself is enabled, since it protects the password manager too.',
      },
      {
        title: 'Turn on two-factor authentication where offered',
        content: 'For your most important accounts (email, banking, Medicare, Social Security), turn on two-factor authentication (2FA) in addition to a strong password — this requires a code sent to your phone in addition to the password, so a stolen password alone cannot get someone in.',
        warning: 'Never share a two-factor code with anyone who calls or texts asking for it, even if they claim to be your bank or a tech support agent. A legitimate company never needs you to read that code aloud.',
      },
    ],
  },

  {
    slug: 'back-to-school-tech-shopping-scams-grandparents',
    title: 'Buying Tech for a Grandchild This Fall? Watch for These Shopping Scams',
    excerpt: 'Back-to-school season brings a spike in fake online stores and too-good-to-be-true deals on laptops and tablets. Here is how to shop safely.',
    category: 'safety-guides',
    tags: ['shopping scam', 'back to school', 'online shopping', 'fake website', 'laptop deals', 'fraud'],
    readTime: '5 min',
    thumbnailEmoji: '🎒',
    publishedAt: '2026-08-04',
    lastVerifiedAt: '2026-08-04',
    difficulty: 'Beginner',
    body: `Every August, many grandparents help pay for a grandchild's back-to-school laptop, tablet, or headphones — and scammers know it. Fake online stores advertising steep discounts on popular electronics brands spike every year during back-to-school season, often appearing in social media ads or search results promising a well-known laptop or tablet at 50–70% off the normal price.

These fake stores are built to look legitimate, sometimes copying a real retailer's photos and layout almost exactly. The warning signs are usually the same: a price dramatically lower than anywhere else, a website that only accepts payment by wire transfer, gift card, or cryptocurrency instead of a credit card, a very new website address, and no way to reach customer service by phone. Shoppers who pay never receive the item, or receive a cheap counterfeit instead of what was advertised.

The safest path is to shop directly through retailers you already know and trust — buying directly from Apple, Best Buy, Amazon, Walmart, Target, or a manufacturer's own website removes most of the risk, even if it means paying a slightly higher price than an unfamiliar "deal" site.

(Sources: Federal Trade Commission consumer alerts — consumer.ftc.gov; Better Business Bureau seasonal scam tracker — bbb.org)`,
    steps: [
      {
        title: 'Shop directly with retailers you already know',
        content: 'Type the address of a familiar retailer (Apple.com, BestBuy.com, Amazon.com, Walmart.com, Target.com) directly into your browser rather than clicking a link from an ad or a search result. This avoids fake lookalike sites entirely.',
      },
      {
        title: 'Treat a huge discount as a warning sign, not a bonus',
        content: 'If a laptop, iPad, or gaming console is priced dramatically below what it costs everywhere else, that is the clearest sign of a scam site — legitimate retailers do not sell popular electronics at 50–70% off during back-to-school season.',
      },
      {
        title: 'Always pay by credit card, never wire transfer or gift card',
        content: 'A credit card gives you dispute rights if an item never arrives or is not as described. If a website insists on payment only by wire transfer, gift card, or cryptocurrency, do not buy — this is one of the most reliable scam signals there is.',
        warning: 'No legitimate retailer requires payment by gift card or cryptocurrency for a normal purchase. If a site insists on it, close the page.',
      },
      {
        title: 'Check for real contact information before buying from an unfamiliar site',
        content: 'Look for a working customer service phone number and a physical business address on the website. If you can only find a contact form or the phone number does not work, treat that as a red flag.',
        tip: 'Quick Tip: Search the store\'s name along with the word "scam" or "reviews" before buying — problems with a fake store are usually reported quickly by other shoppers.',
      },
      {
        title: 'If you already paid a suspicious site',
        content: 'Contact your credit card company immediately to dispute the charge, and report the site to the FTC at reportfraud.ftc.gov and to the Better Business Bureau at bbb.org/scamtracker. Acting quickly improves the chance of getting your money back.',
      },
    ],
  },
];
