// guides-batch-137 — Auto-generated by creative-loop on 2026-05-05
// Topics: How to Use the Built-In Passwords App on iPhone; Use Voice Typing on iPhone to Send Text Messages and Emails Faster

import type { Guide } from './guides';

export const guidesBatch137: Guide[] = [
  {
    slug: 'set-up-iphone-passwords-app',
    title: 'How to Use the Built-In Passwords App on iPhone',
    excerpt: 'iPhone now includes a free Passwords app that saves and auto-fills your passwords across all your devices. Here is how to set it up.',
    category: 'safety-guides',
    tags: ['passwords', 'iphone', 'apple', 'security', 'seniors', 'icloud'],
    readTime: '6 min',
    thumbnailEmoji: '🛡️',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Starting with iOS 18, every iPhone includes a free Passwords app that saves your passwords, fills them in automatically when you sign into websites and apps, warns you about reused or compromised passwords, and syncs everything to your other Apple devices through iCloud.

This means you do not need to remember every password. You only need to remember your iPhone passcode (or use Face ID/Touch ID), and the Passwords app handles the rest. It is also a free alternative to paid password managers like 1Password or LastPass — for many people, it covers everything they need.

Passwords saved here are encrypted with end-to-end encryption, meaning even Apple cannot read them. Only you, signed into your Apple ID with Face ID or your passcode, can unlock the vault.

(Sources: Apple Support — Passwords app, support.apple.com/passwords)`,
    steps: [
      {
        title: 'Find the Passwords app on your iPhone',
        content: 'On any iPhone running iOS 18 or later, the Passwords app is pre-installed. Swipe left until you reach the App Library, search for "Passwords," and tap it. The first time you open it, the iPhone asks for Face ID, Touch ID, or your passcode to unlock the vault.',
      },
      {
        title: 'Let Passwords import what you already have',
        content: 'If you have ever asked Safari to save a password, those passwords are already in the Passwords app. Look at the list — you may be surprised how many are there. The app organizes them alphabetically by website name.',
      },
      {
        title: 'Add a password manually',
        content: 'Tap the "+" button to add a password. Enter the website (like "chase.com"), your username, and the password. Save. Next time you visit that website on your iPhone or Mac, the iPhone offers to fill in your saved password automatically.',
        tip: 'Quick Tip: Use a unique password for every website. The Passwords app suggests a strong unique password every time you sign up for a new site — tap "Use Strong Password" when offered. The app remembers it for you.',
      },
      {
        title: 'Turn on Sign in with Apple where possible',
        content: 'Many websites offer "Sign in with Apple" as a sign-in option. This skips passwords entirely — Apple verifies your identity and the website never sees your real email address. Where available, use this option to reduce your password list.',
      },
      {
        title: 'Set up sharing with a spouse or family member',
        content: 'For shared accounts (like a streaming service or shared utilities), tap a password, then "Share with Family." Family members you have added in your iCloud Family Sharing group can view and use the shared password. Useful when one spouse manages most accounts but the other needs occasional access.',
      },
      {
        title: 'Review security warnings',
        content: 'Tap "Security" inside the app. The Passwords app shows you any passwords that have been part of known data breaches (when companies accidentally leak passwords), reused across sites, or weak. Update these one by one — the app provides a link directly to each website\'s password change page.',
      },
    ],
  },

  {
    slug: 'use-iphone-voice-typing-dictation',
    title: 'Use Voice Typing on iPhone to Send Text Messages and Emails Faster',
    excerpt: 'Speak instead of type — iPhone\'s built-in voice typing is fast, accurate, and works in any app where you can type. Here is how.',
    category: 'phone-guides',
    tags: ['dictation', 'voice-typing', 'iphone', 'accessibility', 'seniors', 'speech'],
    readTime: '4 min',
    thumbnailEmoji: '📱',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Typing on a phone keyboard can be slow and frustrating, especially with arthritis or stiff fingers. iPhone has built-in voice typing that lets you speak whatever you want to write, and the iPhone types it for you in real time. It works in text messages, emails, Notes, search bars — anywhere you can type.

The voice recognition is excellent (much better than it was a few years ago) and works without an internet connection on iPhone 12 and newer. Punctuation is added automatically, and you can also speak punctuation marks aloud ("comma," "period," "question mark") for full control.

You do not need to download anything or set up an account. Voice typing is free and built in.

(Sources: Apple Support — Dictation, support.apple.com/HT207525)`,
    steps: [
      {
        title: 'Turn on Dictation in Settings',
        content: 'Open Settings → General → Keyboard. Make sure "Enable Dictation" is turned on (green). This is on by default on most iPhones, but worth checking.',
      },
      {
        title: 'Tap any text field and look for the microphone icon',
        content: 'In any app where you can type — Messages, Mail, Notes, Safari search — tap to start typing. On the on-screen keyboard, look for a small microphone icon in the bottom right corner. Tap it. The microphone fills the keyboard area and starts listening.',
      },
      {
        title: 'Speak your message naturally',
        content: 'Speak as you would talk to a friend. The iPhone types what you say in real time. You can pause, think, and continue — voice typing waits up to 60 seconds before stopping. Tap anywhere to stop early.',
        tip: 'Quick Tip: Voice typing now adds punctuation automatically based on the rhythm of your speech. You do not have to say "period" or "comma" — but you can if you prefer more control.',
      },
      {
        title: 'Speak special characters when needed',
        content: 'For things voice typing cannot guess, speak them. Examples: "new line" creates a line break; "smiley face" inserts a 🙂; "exclamation point" inserts !; "ellipsis" inserts ...; "all caps" before a word makes it ALL CAPS. These are useful in emails or longer messages.',
      },
      {
        title: 'Edit with your finger after dictating',
        content: 'After voice typing, your usual keyboard returns. You can correct any word the iPhone misheard by tapping it and selecting an alternate from the suggestions, or tapping and editing manually. Most short messages need no edits.',
      },
      {
        title: 'Use voice typing in any language you speak',
        content: 'iPhone can dictate in over 30 languages including Spanish, French, Italian, German, Mandarin, and Japanese. Add a language in Settings → General → Keyboard → Keyboards → Add New Keyboard. After adding, the microphone icon respects whichever keyboard is currently active.',
      },
    ],
  },
];
