// guides-batch-140 — Auto-generated by creative-loop on 2026-05-05
// Topics: How to Use Uber or Lyft for the First Time; Set Up Medication Reminders on iPhone (Built-In, Free)

import type { Guide } from './guides';

export const guidesBatch140: Guide[] = [
  {
    slug: 'use-uber-lyft-first-time-seniors',
    title: 'How to Use Uber or Lyft for the First Time',
    excerpt: 'Uber and Lyft let you hail a ride from your phone — no cash, no waving down a taxi. Here is the step-by-step for first-time riders.',
    category: 'app-guides',
    tags: ['uber', 'lyft', 'rideshare', 'seniors', 'transportation'],
    readTime: '6 min',
    thumbnailEmoji: '🛒',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `Uber and Lyft are smartphone apps that let you call for a ride from any address to any address. A driver in a regular car (not a taxi) picks you up, drives you to your destination, and the fare is automatically charged to a credit card you saved in the app. There is no cash and no tip pressure (tips are optional and easy to leave through the app).

Both services are popular with seniors who no longer drive, or who want a ride home from a medical appointment, dinner with friends, or a place where parking is hard to find. Many cities have specific senior programs — including discounted rides through Lyft's Lyft Up partnership and Uber Health for medical appointments.

The first ride is the most intimidating. After the first one, every subsequent ride takes about 30 seconds to book. This guide focuses on Uber but Lyft works almost identically.

(Sources: Uber Help, help.uber.com; Lyft Help, help.lyft.com; AARP — Rideshare for seniors, aarp.org/ride-share)`,
    steps: [
      {
        title: 'Download the Uber app and create an account',
        content: 'Open the App Store (iPhone) or Google Play (Android) and search for "Uber." Install the official app — look for the black square with white "Uber" text. Open it and tap "Sign up" or "Create an account." Enter your phone number; Uber sends a 6-digit code to confirm. Then add your name, email, and a credit or debit card.',
        warning: 'Use the official Uber app only. Several scam apps with similar names exist on the app store. The real Uber has tens of millions of reviews.',
      },
      {
        title: 'Set your home address',
        content: 'Tap the menu icon (three lines) → Settings → Saved Places. Add your home address as "Home." Add common destinations like your doctor or grocery store. Saved places make booking faster — you can tap "Home" to set it as the destination instead of typing every time.',
      },
      {
        title: 'Book your first ride',
        content: 'Open the app. The home screen has a "Where to?" search bar. Tap it. Type or select a saved destination. Uber shows you ride options (UberX is the basic, cheapest one — pick that). It also shows the fare estimate and how long until a driver arrives. Tap "Choose UberX" then "Confirm UberX."',
      },
      {
        title: 'Wait for the driver and verify the car',
        content: 'After booking, the app shows the driver\'s name, photo, license plate, and car color. When they arrive, verify all three before getting in: license plate, car color, and driver name. The driver should also confirm your name. If anything does not match, do not get in — call another ride.',
        tip: 'Quick Tip: Wait inside or in a well-lit area until you see the actual car arrive. The app shows a live map of the driver approaching.',
      },
      {
        title: 'During and after the ride',
        content: 'You do not need to give the driver directions — they have GPS and your destination already. You can sit anywhere in the car (front or back). When you arrive, get out — there is no need to pay or sign anything. The fare is automatically charged. The app then asks you to rate the driver (5 stars is normal for a fine ride) and lets you add an optional tip.',
      },
      {
        title: 'Save the support number in case of issues',
        content: 'For any problem during a ride, tap the shield icon in the app for safety options including Emergency Assistance (which calls 911 with your live location). For non-emergency issues like being charged the wrong amount, go to Help in the app and tap "Report Issue." Both Uber and Lyft refund mistakes promptly when reported through the app.',
      },
    ],
  },

  {
    slug: 'set-up-iphone-medication-reminders',
    title: 'Set Up Medication Reminders on iPhone (Built-In, Free)',
    excerpt: 'iPhone\'s Health app has a free Medications feature that reminds you to take pills, tracks your history, and warns about interactions.',
    category: 'health-tech',
    tags: ['medications', 'iphone', 'health', 'reminders', 'apple', 'seniors'],
    readTime: '5 min',
    thumbnailEmoji: '🏥',
    publishedAt: '2026-05-05',
    lastVerifiedAt: '2026-05-05',
    difficulty: 'Beginner',
    body: `iPhone's Health app includes a free Medications feature that reminds you when to take each pill, lets you log doses you have taken, tracks your history over time, and warns you about possible interactions between medications. It is private — Apple does not see your data — and works without a subscription or extra app.

You enter each medication once (name, dosage, schedule, and what it looks like). The iPhone sends a notification at each dose time. You tap to confirm you took it. The Health app then saves the history, which you can show your doctor at your next appointment.

The Medications feature works on iPhone running iOS 16 or later. Older iPhones can use the Reminders app for a simpler version.

(Sources: Apple Support — Medications in Health, support.apple.com/HT213355; FDA Drug Information, fda.gov/drugs)`,
    steps: [
      {
        title: 'Open the Health app and find Medications',
        content: 'On any iPhone, the Health app is pre-installed (white icon with a red heart). Open it. Tap "Browse" at the bottom. Scroll down and tap "Medications." Tap "Add Medication."',
      },
      {
        title: 'Enter each medication',
        content: 'Type the medication name (the iPhone offers a list as you type). Pick the form (tablet, capsule, liquid, inhaler), strength (like 10 mg), and the dosage you take (one pill, two pills). Set the schedule — daily at 8 AM, twice a day, or "as needed." You can add a photo of what the pill looks like.',
        tip: 'Quick Tip: Add medications one at a time. Even over-the-counter ones like aspirin or vitamin D are worth adding — the Health app warns of interactions across the whole list.',
      },
      {
        title: 'Turn on reminders',
        content: 'After adding a medication, tap "Add Reminders" to schedule notifications. The iPhone reminds you at each dose time. You can mark the reminder as "Taken" to log it, or "Skip" if you missed a dose. Either way, the Health app records what happened.',
      },
      {
        title: 'Check for interactions',
        content: 'After adding two or more medications, tap "Interactions" in the Medications screen. The iPhone shows any known interactions or warnings. This is a starting point — always discuss interactions with your doctor or pharmacist — but it can highlight issues to ask about.',
      },
      {
        title: 'Share your medication list with family or doctor',
        content: 'In Health → Sharing, you can share medication info with a family member who also has an iPhone. They see your list, your schedule, and whether you have been taking your medications on time. For doctors, tap a medication, then "Share Medication" to email or print a summary.',
      },
      {
        title: 'For older iPhones: use the Reminders app instead',
        content: 'If your iPhone is too old for the Medications feature, the built-in Reminders app works as an alternative. Open Reminders, tap +, type "Take morning pills" or any medication name, tap the (i) icon, and set a daily repeating time. The reminder appears on your lock screen at that time every day. Less rich than the Health app, but free and reliable.',
      },
    ],
  },
];
