// guides-batch-331 — Auto-generated by 90-day sprint task on 2026-07-29
// Topics: Porch pirate / package theft prevention; Claude AI mobile app basics;
// Social Security 2027 COLA timeline; Buy Now Pay Later risks; disaster
// relief charity scams

import type { Guide } from './guides';

export const guidesBatch331: Guide[] = [
  {
    slug: 'porch-pirate-package-theft-protection',
    title: 'How to Stop Porch Pirates From Stealing Your Packages',
    excerpt: 'Package theft cost US shoppers nearly $15 billion last year. Here are low-cost, practical ways to protect deliveries left on your porch.',
    category: 'safety-guides',
    tags: ['package theft', 'porch pirates', 'safety', 'deliveries', 'home security', 'amazon'],
    readTime: '6 min',
    thumbnailEmoji: '📦',
    publishedAt: '2026-07-29',
    lastVerifiedAt: '2026-07-29',
    difficulty: 'Beginner',
    body: `Package theft, often called "porch piracy," is a fast-growing problem. According to the 2025 SafeWise U.S. Package Theft Report, an estimated 104 million packages were taken from doorsteps nationwide in a single year — about 248,000 every day — with a total cost to consumers of nearly $15 billion. The average stolen package was worth about $143.

The good news is that most of this is preventable, and it does not require expensive equipment. One finding from the same report stands out: 98% of stolen packages were visible from the street. That single fact points to the most effective fix — get packages out of sight, or get someone to grab them before a thief does.

You do not need a full security system to cut your risk dramatically. A combination of a few free or low-cost habits — tracking deliveries, choosing pickup points, and asking a neighbor to watch for boxes — closes most of the opportunity a porch pirate looks for. If you want a bit more protection, a video doorbell in the $60–$100 range covers the rest.

Report any theft to your local police non-emergency line and to the retailer — most major retailers, including Amazon, will replace or refund a package confirmed stolen after delivery, especially with photo or video evidence.

(Sources: SafeWise 2025 U.S. Package Theft Report — safewise.com; Federal Communications Commission consumer guidance — fcc.gov)`,
    steps: [
      {
        title: 'Turn on delivery tracking and alerts',
        content: 'Open the Amazon, UPS, FedEx, or USPS app and turn on text or push notifications for "out for delivery" and "delivered." Knowing the moment a package lands on your porch lets you bring it in within minutes instead of hours.',
      },
      {
        title: 'Ask packages to be left somewhere hidden from the street',
        content: 'Many delivery apps let you leave instructions like "please leave behind the porch railing" or "leave at the side door." A package tucked out of direct view from the street is far less likely to be noticed and taken — remember, 98% of stolen packages were visible from the road.',
      },
      {
        title: 'Use a pickup locker or store pickup for valuable items',
        content: 'For anything expensive, choose "Amazon Locker," a UPS Access Point, or in-store pickup instead of home delivery. These are staffed or secured locations, so there is no window of time for a package to sit unattended.',
        tip: 'Quick Tip: Many pharmacies and grocery stores host Amazon Lockers for free — search "Amazon Locker near me" in the Amazon app to find one close to you.',
      },
      {
        title: 'Recruit a neighbor or set a pickup window',
        content: 'If you are often out during delivery hours, ask a trusted neighbor to bring packages in for you, or schedule deliveries for a day you know you will be home. Many carriers also let you choose a specific delivery window in their app.',
      },
      {
        title: 'Consider a video doorbell for extra peace of mind',
        content: 'A video doorbell (Ring, Blink, Wyze, or similar, typically $60–$100) lets you see and speak to whoever is on your porch in real time, and records footage if a theft does happen. This is optional — the free habits above prevent most theft on their own — but it adds a layer of protection and gives police useful evidence if something is taken.',
        warning: 'If a theft does happen, do not confront the person in progress. Report it to police and the retailer instead, and share any doorbell footage you have.',
      },
    ],
  },

  {
    slug: 'claude-ai-app-basics-for-seniors',
    title: 'Getting Started with the Claude App on Your Phone',
    excerpt: 'Claude is a free AI assistant app for iPhone and Android that can answer questions, read documents, and describe photos. Here is how to start using it.',
    category: 'ai-guides',
    tags: ['claude', 'ai', 'mobile app', 'chatbot', 'anthropic', 'ai assistant'],
    readTime: '6 min',
    thumbnailEmoji: '🤖',
    publishedAt: '2026-07-29',
    lastVerifiedAt: '2026-07-29',
    difficulty: 'Beginner',
    body: `Claude is an AI assistant made by a company called Anthropic. It works like ChatGPT: you ask it a question, and it answers in plain, everyday text. Claude has its own free app for iPhone and Android, with a few features worth knowing.

The app is free to download and use. There is also a paid "Pro" plan for people who want higher usage limits, but you do not need it to try Claude. Once the app is installed, you can type a question, use your voice instead of typing, take a photo and ask Claude to describe or explain it, or upload a document — like a PDF of a bill or a letter — and ask Claude to explain it in plain language.

Claude is good at everyday tasks. It can draft an email, explain a confusing insurance letter, plan a trip, or answer a question you would otherwise search for online. It cannot browse the live internet for every answer, and it can sometimes get facts wrong. Treat its answers as a helpful starting point, not a final word — especially for anything medical, legal, or financial.

As with any AI chat app, keep sensitive information out of the conversation. Never type your Social Security number, full bank account numbers, or passwords. Claude does not need that information to help you, and leaving it out protects your privacy.

(Source: Anthropic — claude.ai/download; Apple App Store and Google Play listings, verified July 2026)`,
    steps: [
      {
        title: 'Download the app',
        content: 'On an iPhone, open the App Store and search "Claude by Anthropic." On an Android phone, open the Google Play Store and search the same name. Tap "Get" or "Install." The app is free.',
      },
      {
        title: 'Create a free account',
        content: 'Open the app and tap "Sign Up." You can sign up with an email address or a Google account. You will get a short code by email — type it in to verify your account.',
      },
      {
        title: 'Ask your first question',
        content: 'Tap the text box at the bottom of the screen and type a question, such as "Explain what a high-deductible health plan is" or "Write a birthday message for my granddaughter." Tap the arrow button to send it. Claude replies in a few seconds.',
      },
      {
        title: 'Try voice input or a photo',
        content: 'Tap the microphone icon to speak your question instead of typing. To ask about something you can see, tap the camera or attachment icon and take or choose a photo. Then ask a question about it — for example, a photo of a prescription label with "What is this medication usually used for?"',
        tip: 'Quick Tip: You can also upload a PDF or photo of a confusing letter or bill and ask, "Can you explain this in plain language?"',
      },
      {
        title: 'Keep sensitive information out of the chat',
        content: 'Never type your full Social Security number, bank or card numbers, or passwords into any AI chat app, including Claude. Describe your situation in general terms instead of pasting an actual account number.',
        warning: 'Treat any medical, legal, or financial answer as a starting point, not a final answer. Confirm important decisions with your doctor, a lawyer, or your bank.',
      },
    ],
  },

  {
    slug: 'social-security-cola-2027-what-to-expect',
    title: "Social Security's 2027 Raise: When You'll Know and What to Expect",
    excerpt: 'The 2027 Social Security cost-of-living increase will be announced in mid-October 2026. Here is how the raise is calculated and when you will see it.',
    category: 'government-civic',
    tags: ['social security', 'cola', 'cost of living adjustment', 'retirement', 'benefits', 'ssa'],
    readTime: '6 min',
    thumbnailEmoji: '🏛️',
    publishedAt: '2026-07-29',
    lastVerifiedAt: '2026-07-29',
    difficulty: 'Beginner',
    body: `Every year, Social Security benefits can go up a little to help keep pace with rising prices. This yearly increase is called a COLA, short for Cost-of-Living Adjustment. It is not an amount Congress votes on. It is calculated automatically, using a government inflation measure called the CPI-W (Consumer Price Index for Urban Wage Earners and Clerical Workers).

The Social Security Administration compares average CPI-W prices from July, August, and September of the current year to those same three months the year before. For the 2027 COLA, that means using July–September 2026 data. The official number will be announced in mid-October 2026, usually alongside a Bureau of Labor Statistics inflation report.

As of mid-2026, no official 2027 COLA figure exists yet. Some retirement-benefit analysts have published early estimates in the high-3% range. But these are only guesses based on partial-year data — not a confirmed number. The real figure will not be final until the October announcement. Treat any number you see in the news before then as a guess, not a fact.

Once the COLA becomes official in October, the Social Security Administration mails a personalized benefit-amount letter in early December. It also posts this letter online in your my Social Security account. Your new, higher payment begins with checks paid in January 2027.

(Sources: Social Security Administration — ssa.gov/cola; Bureau of Labor Statistics CPI-W data — bls.gov)`,
    steps: [
      {
        title: 'Understand it is automatic — there is nothing to apply for',
        content: 'The COLA applies automatically to everyone already getting Social Security or SSI benefits. You do not need to call or apply. It is added to your existing monthly payment without any action from you.',
      },
      {
        title: 'Set up (or check) your my Social Security account',
        content: 'Go to ssa.gov/myaccount on a computer or phone browser and sign in, or create a free account if you do not have one. This is where the Social Security Administration posts your personal COLA notice in December, often before the mailed letter arrives.',
      },
      {
        title: 'Watch for the official announcement in mid-October',
        content: 'The Social Security Administration will announce the confirmed 2027 COLA percentage in mid-October 2026. Check ssa.gov directly for the announcement, rather than trusting early news estimates — those can change.',
      },
      {
        title: 'Expect your new amount in December, effective January',
        content: 'Your personal notice, showing your new 2027 monthly benefit amount, usually arrives by mail and in your online account in early December 2026. Your higher payment itself starts with the check or deposit paid in January 2027.',
      },
      {
        title: 'Be alert for COLA-related scam calls',
        content: 'Every fall, scammers call claiming they can help you "get your COLA increase early," or that they need your bank information to "process" the raise. The Social Security Administration never calls asking for payment or your full bank account number to apply a COLA. The increase happens automatically, with no action needed from you.',
        warning: 'Hang up on any call asking for personal or banking information to "release" your Social Security increase, and report it to the SSA Office of the Inspector General at oig.ssa.gov.',
      },
    ],
  },

  {
    slug: 'buy-now-pay-later-basics-and-risks',
    title: 'Buy Now, Pay Later: How It Works and Where the Risk Is',
    excerpt: 'Apps like Klarna, Afterpay, and Affirm let you split a purchase into payments at checkout. Here is how they work and where people get into trouble.',
    category: 'financial-tech',
    tags: ['buy now pay later', 'bnpl', 'klarna', 'afterpay', 'affirm', 'budgeting', 'online shopping'],
    readTime: '6 min',
    thumbnailEmoji: '🛍️',
    publishedAt: '2026-07-29',
    lastVerifiedAt: '2026-07-29',
    difficulty: 'Beginner',
    body: `Buy Now, Pay Later (BNPL) is a payment option offered at checkout on many online and in-store purchases. Services like Klarna, Afterpay, Affirm, and PayPal's "Pay in 4" offer it. Instead of paying the full price at once, you split it into smaller payments — commonly four payments every two weeks, or a longer monthly plan for bigger purchases.

The appeal is real. Many BNPL plans charge no interest if you pay on time, and approval is usually instant with only a soft credit check, or none at all. That is different from a traditional credit card application.

The risk shows up in two places. First, because each payment looks small, it is easy to open several BNPL plans across different stores and lose track of the total you owe and when each payment is due. Regulators call this pattern "loan stacking." A March 2025 Bankrate survey found that about 49% of BNPL users had at least one problem with the payment method, most often a missed payment or a surprise fee. Second, BNPL purchases do not always carry the same protections as a credit card. If an item arrives damaged or never arrives, getting your money back can take longer and involve more steps than a simple credit card chargeback.

Regulators including the Consumer Financial Protection Bureau and Federal Trade Commission have increased scrutiny of BNPL providers' fee disclosures and dispute processes in 2026. That is a sign the risks are being taken seriously. But the rules still vary by provider, so read the terms before you commit.

(Sources: Consumer Financial Protection Bureau — consumerfinance.gov; Federal Trade Commission — ftc.gov; Bankrate 2025 BNPL survey)`,
    steps: [
      {
        title: 'Understand the typical plan structure',
        content: 'Most BNPL "Pay in 4" plans split a purchase into 4 equal payments. One is due at checkout, and the other three come every two weeks after. Larger purchases, like furniture or electronics, sometimes offer longer monthly plans instead, which may include interest. Read the terms shown before you confirm.',
      },
      {
        title: 'Keep every BNPL plan in one place',
        content: 'If you use more than one BNPL app, track each purchase, the total owed, and the due dates in one place — a notebook, spreadsheet, or your phone\'s notes app. This prevents the most common problem: forgetting a payment because it is spread across several apps.',
      },
      {
        title: 'Turn on payment reminders',
        content: 'Inside the Klarna, Afterpay, or Affirm app, look for "Notifications" or "Payment Reminders" in settings and turn them on. A missed payment can trigger a late fee, and in some plans, interest on the full remaining balance.',
      },
      {
        title: 'Check the return and dispute policy before you buy',
        content: 'Before using BNPL for a purchase, check the retailer\'s return policy and the BNPL provider\'s dispute process for a damaged or missing item. Protections vary by provider, and are sometimes weaker than a credit card\'s built-in dispute rights.',
        tip: 'Quick Tip: For a purchase you are unsure about, a credit card with purchase protection may give you a faster, more familiar path to a refund than a BNPL plan.',
      },
      {
        title: 'Treat it as a loan, not free money',
        content: 'A BNPL plan is a short-term loan, even when it charges no interest. Only use it for a purchase you could otherwise afford in full. That way, a missed payment — say, because of a bank holiday or a forgotten reminder — does not turn into a fee or a hit to your credit.',
        warning: 'Some BNPL providers now report your payment history to credit bureaus. A missed payment can affect your credit score, not just cost you a late fee.',
      },
    ],
  },

  {
    slug: 'disaster-relief-charity-scam-guide',
    title: 'How to Avoid Fake Charities After a Hurricane, Flood, or Wildfire',
    excerpt: 'Scammers move fast after a disaster, setting up fake charities and fake FEMA calls within days. Here is how to verify a charity before you give.',
    category: 'safety-guides',
    tags: ['scam', 'charity', 'fema', 'disaster relief', 'donation', 'fraud'],
    readTime: '5 min',
    thumbnailEmoji: '🌀',
    publishedAt: '2026-07-29',
    lastVerifiedAt: '2026-07-29',
    difficulty: 'Beginner',
    body: `After a hurricane, flood, wildfire, or other disaster makes the news, two kinds of scams reliably follow within days. First, fake charities ask for donations. Second, callers pretend to be FEMA (the Federal Emergency Management Agency) and ask for money or personal information from people in the affected area.

Fake charities often register web addresses that include the disaster's location or name, paired with words like "help," "relief," or "fund." They push donation requests through texts, emails, and social media posts. These are designed to look urgent and legitimate at a glance — which is exactly why a quick pause before donating matters.

FEMA scams work differently. A caller claims to represent FEMA. They either ask for a fee to "process" a disaster assistance application, or ask the survivor to confirm banking information to "release" a grant. FEMA's own consumer guidance says this is a reliable red flag by itself: FEMA never charges a fee for disaster assistance applications, inspections, or grants. FEMA also never asks a survivor to confirm full banking details over an unsolicited call. Wearing a FEMA-style shirt or jacket is not proof of identity either — scammers have used both.

The safest approach to either scam is the same: verify independently before you give any money or information. Look up the charity or agency yourself, rather than trusting a link or phone number a stranger gave you.

(Sources: FEMA.gov press releases on post-disaster fraud; Federal Communications Commission consumer guides — fcc.gov; AARP Fraud Watch Network — aarp.org)`,
    steps: [
      {
        title: 'Never give through a link in a text, email, or social post',
        content: 'If you want to donate after a disaster, close the message. Go directly to a charity\'s official website by typing the address yourself, or search for the charity by name. Do not tap a "Donate Now" link sent to you directly — it may lead to a fake, lookalike donation page.',
      },
      {
        title: 'Verify the charity before giving',
        content: 'Check the charity\'s standing at Give.org (BBB Wise Giving Alliance), Charity Navigator, or CharityWatch before donating. These sites show how much of a donation actually reaches the cause, versus overhead. They also flag charities with a poor track record or no verifiable history.',
      },
      {
        title: 'Know that FEMA never asks for money or full bank details by phone',
        content: 'FEMA does not charge for disaster assistance applications, home inspections, or grants. FEMA will not call and ask you to confirm your full bank account number. If a caller claiming to be FEMA asks for either, hang up — it is a scam.',
        warning: 'A uniform, badge, or FEMA-branded clothing is not proof of identity. Ask for a name and badge number, then hang up and call FEMA directly at 1-800-621-3362 to verify before giving any information.',
      },
      {
        title: 'Apply for real FEMA assistance the safe way',
        content: 'If a disaster affected you and you want to apply for federal assistance, go directly to DisasterAssistance.gov or call 1-800-621-3362 yourself. Do not respond to an unsolicited call, text, or email offering to help you apply.',
      },
      {
        title: 'Report suspected scams',
        content: 'Report a suspected FEMA impersonation call to the FEMA Disaster Fraud Hotline at 1-866-720-5721. Report a suspicious charity to your state\'s Attorney General consumer protection office or to the FTC at reportfraud.ftc.gov.',
      },
    ],
  },
];
