// guides-batch-330 — Auto-generated by 90-day sprint task on 2026-07-28
// Topics: Fake Geek Squad renewal email scam; Grocery store loyalty apps;
// Apple Cash Family spending limits; iPhone Mail app Categories; turning off
// targeted ads on Facebook/Instagram/Google; bill pay reminder alerts

import type { Guide } from './guides';

export const guidesBatch330: Guide[] = [
  {
    slug: 'fake-geek-squad-renewal-email-scam',
    title: 'The Fake Geek Squad Renewal Email Scam: How to Spot It',
    excerpt: 'An email claiming your Best Buy Geek Squad plan renewed for $400+ is one of the most reported tech scams right now. Here is how to tell it from a real receipt.',
    category: 'safety-guides',
    tags: ['scam', 'geek squad', 'best buy', 'phishing', 'email', 'fraud'],
    readTime: '5 min',
    thumbnailEmoji: '🛡️',
    publishedAt: '2026-07-28',
    lastVerifiedAt: '2026-07-28',
    difficulty: 'Beginner',
    body: `An email arrives that looks like a receipt from Best Buy's Geek Squad. It says your "Total Tech Support" membership renewed automatically and charged your card several hundred dollars. There is a phone number to call if you want a refund or did not authorize the charge. This is one of the most reported tech scams tracked by the FBI's Internet Crime Complaint Center (IC3), and it has cost victims hundreds of millions of dollars nationwide.

The scam does not depend on you having a real Geek Squad account. It works on volume, sending the fake receipt to as many people as possible. If you never signed up for Geek Squad, the email may still worry you enough to call the number out of concern that someone charged your card without permission. That is the trap. The phone number does not connect you to Best Buy at all — it connects you to a scammer posing as a "billing department representative."

Once you call, the scammer walks you through "canceling" the charge. This usually means asking you to install remote-access software on your computer or phone, which gives the scammer control of your device. From there, they may ask you to log into your bank account "so we can process your refund," which lets them see your balance and move money out, or they may claim they "accidentally" refunded too much and ask you to send the difference back through a gift card or wire transfer.

The email itself often has real Best Buy logos and formatting copied from an actual receipt, so it can look convincing at a glance. What gives it away is usually the total dollar amount (often $300 to $500, higher than typical), a sense of urgency to call within 24 hours, and a phone number that is not the real Best Buy customer service line.

(Sources: FBI Internet Crime Complaint Center — ic3.gov; Better Business Bureau Scam Tracker — bbb.org/scamtracker)`,
    steps: [
      {
        title: 'Do not call the number in the email',
        content: 'No matter how real the receipt looks, do not call any phone number printed inside the email. If you want to check whether you actually have a Geek Squad membership, go to bestbuy.com yourself and log into your real account, or call the number printed on the back of a Best Buy card or a past real receipt.',
        warning: 'Never let anyone from an unexpected email install remote-access software on your computer. This gives them full control of your device and everything on it.',
      },
      {
        title: 'Check whether you actually have a Best Buy or Geek Squad account',
        content: 'Open a web browser and type bestbuy.com yourself. Log into your account (or try to create one with your email if you are not sure you have one). If there is no Geek Squad membership listed on your real account, the email is fake and you owe nothing.',
      },
      {
        title: 'Look for the classic warning signs',
        content: 'Fake renewal emails usually share a few features: a large charge amount, a short deadline to "dispute" it, a phone number instead of a link to your real account, and small spelling or formatting errors if you look closely at the sender\'s email address.',
        tip: 'Quick Tip: Hover your mouse over the sender\'s name (do not click) to see the actual email address. Real Best Buy emails come from a bestbuy.com address, not a random domain.',
      },
      {
        title: 'Report the email',
        content: 'Forward the email to Best Buy\'s abuse team by checking bestbuy.com for their current reporting address, and file a report at ic3.gov (FBI) or reportfraud.ftc.gov (Federal Trade Commission). This helps investigators track the scam network sending these emails.',
      },
      {
        title: 'If you already called and gave access, act fast',
        content: 'If you installed anything the caller asked for, or gave them remote access to your computer, disconnect from the internet, restart your computer, and run a full antivirus scan. If you shared bank information, call your bank immediately using the number on your card (not one the scammer gave you) and ask them to watch your account and consider freezing it.',
      },
    ],
  },

  {
    slug: 'grocery-store-loyalty-apps-savings-guide',
    title: 'Grocery Store Loyalty Apps: Are They Worth Using?',
    excerpt: 'Kroger, Safeway, Publix, and other grocery chains have free apps with digital coupons and fuel points. Here is how they work and how much they can save you.',
    category: 'buying-guides',
    tags: ['grocery', 'savings', 'apps', 'coupons', 'loyalty program', 'budgeting'],
    readTime: '6 min',
    thumbnailEmoji: '🛒',
    publishedAt: '2026-07-28',
    lastVerifiedAt: '2026-07-28',
    difficulty: 'Beginner',
    body: `Most large grocery chains — Kroger, Safeway, Albertsons, Publix, Giant, Stop & Shop, and others — offer a free loyalty app that connects to a rewards card or phone number at checkout. These apps hold digital coupons you "clip" ahead of time, track points toward free groceries or gas discounts, and sometimes show you personalized deals based on what you tend to buy.

The core idea is the same across chains, even though the names differ. You create a free account with your phone number or email. In the store's app, you browse a list of digital coupons and tap "clip" on the ones you want. At checkout, you enter your phone number or scan a barcode from the app, and any clipped coupons apply automatically — no printing or cutting paper coupons required. Many chains also give you points for every dollar spent, which build toward a discount on gas at partner stations or a dollar-off coupon on a future grocery trip.

The real savings vary by household, but many shoppers report saving 5 to 15 percent on their regular grocery bill just by clipping relevant digital coupons before each shopping trip and using their loyalty number at checkout — savings that happen automatically and require no extra spending or subscription fee. The apps are free, and using them costs nothing beyond a few minutes spent browsing coupons before you shop.

One thing to watch for: some grocery apps show you "member pricing" that is not available without scanning your loyalty card, meaning skipping the app can mean paying a higher shelf price on hundreds of items. If you already shop regularly at one of these stores, setting up the free loyalty app is almost always worth the ten minutes it takes.

(Sources: Individual retailer support pages — kroger.com/i/how-to-clip-coupons, publix.com, safeway.com; Consumer Reports — consumerreports.org)`,
    steps: [
      {
        title: 'Find your grocery store\'s app in the app store',
        content: 'Open the App Store (iPhone) or Google Play Store (Android). Search for your regular grocery store by name — for example "Kroger," "Safeway," or "Publix." Download the official app, which will have the store\'s real logo and be published by the store\'s company name.',
      },
      {
        title: 'Create a free loyalty account',
        content: 'Open the app and tap "Sign Up" or "Create Account." You will typically enter your name, email, and a phone number. Some stores mail you a physical loyalty card too, but the phone number usually works at checkout without needing the physical card.',
        tip: 'Quick Tip: Use the same phone number every time you shop at that store, even in person without the app open, so cashiers can look up your rewards and coupons by typing your number.',
      },
      {
        title: 'Browse and "clip" digital coupons before you shop',
        content: 'Inside the app, look for a "Coupons," "Deals," or "For You" section. Tap each coupon you want — this is often called "clipping" the coupon. Clipped coupons apply automatically when you check out with your loyalty number, no printing needed.',
      },
      {
        title: 'Check your points and rewards regularly',
        content: 'Most apps show a running point or reward balance on the home screen. Points often convert to gas discounts at partner stations or a dollar amount off a future order once you hit a certain threshold. Check this every few weeks so rewards do not expire unused.',
      },
      {
        title: 'Watch for the "member price" difference',
        content: 'Some stores show two prices on the shelf tag: a regular price and a lower "member" or "loyalty" price. Scanning your phone number or loyalty card at checkout is what unlocks the lower price, so always use it even if you did not clip any coupons that trip.',
      },
    ],
  },

  {
    slug: 'apple-cash-family-spending-limits-for-kids',
    title: 'How to Set Spending Limits on Apple Cash for Grandkids',
    excerpt: 'Apple Cash Family lets you send a grandchild money with spending limits and purchase notifications, so you can help out without losing track of how it is spent.',
    category: 'financial-tech',
    tags: ['apple cash', 'family sharing', 'grandchildren', 'parental controls', 'money', 'iphone'],
    readTime: '6 min',
    thumbnailEmoji: '💳',
    publishedAt: '2026-07-28',
    lastVerifiedAt: '2026-07-28',
    difficulty: 'Intermediate',
    body: `Apple Cash Family is a version of Apple Cash made for children and teens in a Family Sharing group. If you want to send a grandchild money for a birthday, allowance, or a purchase, Apple Cash Family sends it right to their iPhone or Apple Watch. It also comes with controls a parent can turn on: spending limits, transaction notifications, and approval required before certain purchases.

Your grandchild needs to already be part of an Apple Family Sharing group, usually set up by their parent. If you are the Family Sharing organizer, or a parent has given you access to the group, you can send money through the Messages app or the Wallet app — much like sending Apple Cash to an adult.

The biggest advantage over cash or a gift card is visibility. Every time the money is used, a notification can go to the parent, showing exactly where and how much was spent. This helps younger grandchildren learn to manage money, since each purchase becomes a small teaching moment instead of a mystery.

If a grandchild does not have their own Apple ID, or is not part of a Family Sharing group, a parent needs to set that up first. This guide covers sending and limiting money once a Family Sharing group already exists — setting up Family Sharing itself is a separate step, usually handled by the parent.

(Sources: Apple Support — support.apple.com/guide/iphone/apple-cash-family; Apple Support — support.apple.com/en-us/HT201087)`,
    steps: [
      {
        title: 'Confirm the grandchild is part of a Family Sharing group',
        content: 'Apple Cash Family only works for children added to an Apple Family Sharing group, usually set up by a parent. Ask the parent to confirm the grandchild\'s Apple ID is part of their Family Sharing group before trying to send money, or ask them to add you as a Family Sharing organizer if you want to manage the account directly.',
      },
      {
        title: 'Open the Wallet app and find Apple Cash Family',
        content: 'On an iPhone that is part of the Family Sharing group, open the Wallet app and tap the Apple Cash card. If the grandchild has Apple Cash Family enabled, you will see their name and balance listed under "Family."',
      },
      {
        title: 'Send money through Messages or Wallet',
        content: 'Open a Messages conversation with the grandchild, tap the Apple Pay button (a dollar sign or the Apple Pay logo), enter the amount, and tap Send. The money appears in their Apple Cash Family balance right away, ready to spend with Apple Pay in stores or apps.',
      },
      {
        title: 'Set or check spending notifications',
        content: 'A parent or the Family Sharing organizer can go to Settings, tap their name, then Family Sharing, then the grandchild\'s name, then Apple Cash to review recent activity and adjust settings like whether purchases need approval first.',
        tip: 'Quick Tip: Turning on purchase notifications means you get a message every time the money is spent, which is a simple way to have a conversation about the purchase afterward instead of guessing where the money went.',
      },
      {
        title: 'Talk with the grandchild about the money before sending it',
        content: 'Apple Cash Family removes some of the mystery around spending, but it still works best paired with a conversation. Let the grandchild know what the money is for (a specific gift, general allowance, or open spending) so the notifications make sense to everyone involved.',
        warning: 'Apple Cash Family transfers usually cannot be reversed once sent and spent, the same as sending cash. Only send amounts you are comfortable with if plans change.',
      },
    ],
  },

  {
    slug: 'ios-mail-app-categories-explained',
    title: 'iPhone Mail App "Categories": What They Are and How to Use Them',
    excerpt: 'Your iPhone Mail app now sorts email into tabs like Primary, Transactions, and Promotions. Here is what each category means and how to move a misfiled email.',
    category: 'communication',
    tags: ['email', 'iphone', 'mail app', 'inbox', 'organization', 'ios'],
    readTime: '5 min',
    thumbnailEmoji: '📧',
    publishedAt: '2026-07-28',
    lastVerifiedAt: '2026-07-28',
    difficulty: 'Beginner',
    body: `If your iPhone Mail app inbox recently started showing tabs across the top, like "Primary," "Transactions," "Updates," and "Promotions," this is Apple's Categories feature. It automatically sorts incoming email into groups based on what the message looks like, similar to a feature Gmail has had for years. The goal: keep personal messages easy to find, while newsletters, receipts, and marketing emails wait in their own tabs instead of mixing in with everything else.

"Primary" holds personal email: messages from people you know, plus anything the app can't confidently sort elsewhere. "Transactions" holds order confirmations, shipping notices, and receipts. "Updates" holds account notifications, newsletters you subscribed to, and similar automated messages. "Promotions" holds marketing emails and sales announcements. The sorting happens automatically based on the sender and content, and it can get things wrong sometimes, especially at first.

You can turn this feature off if you prefer one simple inbox. Or keep it on and check each tab when you have a moment, like checking separate folders. Many people find "Primary" alone is enough for daily use, and check the other tabs less often, maybe once a week, to scan for anything important that got misfiled.

If an email lands in the wrong category, say a message from family ends up in "Updates," you can move it. The Mail app will remember your correction for similar emails from that sender next time.

(Source: Apple Support — support.apple.com/guide/iphone/organize-email-in-lists-or-by-category)`,
    steps: [
      {
        title: 'Open Mail and look for the category tabs',
        content: 'Open the Mail app and go to your inbox. If Categories is turned on, you will see a row of tabs near the top, such as "Primary," "Transactions," "Updates," and "Promotions." Tap any tab to see only the emails sorted into that group.',
      },
      {
        title: 'Move a misfiled email to the correct category',
        content: 'If you find an important email in the wrong tab, swipe left on it slightly or tap and hold, then look for an option to move it. On newer versions of Mail, you can tap the category label at the top of an open email and choose a different category from the list that appears.',
        tip: 'Quick Tip: Moving one email from a sender often teaches Mail to sort future emails from that same sender correctly, so future messages from grandkids or friends stay in Primary automatically.',
      },
      {
        title: 'Check the less-important tabs periodically',
        content: 'Set a habit of checking "Updates" and "Promotions" once every few days rather than every time you open your phone. This keeps you from missing a real deal or account notice without needing to see every marketing email as soon as it arrives.',
      },
      {
        title: 'Turn Categories off if you prefer one single inbox',
        content: 'Open the Settings app, scroll down and tap "Mail," then look for an option related to "Categorized Inbox" or "Organize by Category" and turn it off. Your inbox will go back to showing every email in one simple list, newest first, the way Mail worked before this feature existed.',
      },
      {
        title: 'Remember this is separate from spam filtering',
        content: 'Categories sorts email that has already made it to your inbox — it does not block spam or scam emails. Continue watching for phishing attempts and suspicious links regardless of which category tab an email lands in.',
        warning: 'A scam email can still land in "Primary" if it looks enough like a personal message. Categories is an organization tool, not a security tool.',
      },
    ],
  },

  {
    slug: 'turn-off-targeted-ads-facebook-instagram-google',
    title: 'How to Turn Off Personalized Ads on Facebook, Instagram, and Google',
    excerpt: 'Facebook, Instagram, and Google track your activity to show "personalized" ads. Here is where the ad settings are hiding and how to turn them off or limit them.',
    category: 'online-privacy',
    tags: ['privacy', 'ads', 'facebook', 'instagram', 'google', 'tracking'],
    readTime: '6 min',
    thumbnailEmoji: '🔒',
    publishedAt: '2026-07-28',
    lastVerifiedAt: '2026-07-28',
    difficulty: 'Beginner',
    body: `If you have ever talked about a product out loud, searched for it once, and then seen ads for it everywhere afterward, you have experienced targeted advertising. Facebook, Instagram, and Google build a profile of your interests based on what you click, search, and spend time looking at, then use that profile to choose which ads to show you. This is not the same as your phone "listening" to your conversations — the tracking happens through your online activity, not your microphone — but it can still feel invasive, and every major platform gives you at least partial control over it.

Turning off personalized ads does not mean you see fewer ads. Ad-supported apps and websites still show the same number of ads either way. What changes is whether those ads are chosen based on your personal activity or shown more generally. Some people prefer fewer creepy, oddly specific ads even if the total number stays the same, while others do not mind the tracking. Either way, having the choice is worth knowing about.

Each company keeps these settings in a slightly different place, and they sometimes move the settings around during app updates, so the exact menu names below may shift slightly over time. The general idea stays the same across all three: look for a section called "Ads," "Ad Preferences," or "Ads Settings" inside your account settings, not inside the general phone settings.

Turning these off is free and reversible — you can turn personalized ads back on the same way if you change your mind.

(Sources: Meta Privacy Center — facebook.com/privacy/center; Google Ads Settings — myadcenter.google.com)`,
    steps: [
      {
        title: 'Facebook: open Ad Preferences',
        content: 'Open the Facebook app, tap the menu (three lines), then Settings & Privacy, then Settings. Look for "Ad Preferences" or search "ads" in the settings search bar. Tap into "Ad Settings" and look for options about "Data about your activity from partners" and "Categories used to reach you" — turn these off or set them to "Not allowed."',
      },
      {
        title: 'Instagram: use the same Meta Ad settings',
        content: 'Since Instagram is owned by Meta (the same company as Facebook), its ad settings live in the same place. Open Instagram, tap your profile picture, tap the menu, go to Settings, then Ads, and look for "Ad Preferences" or "Data about your activity from partners" to adjust the same way as Facebook.',
        tip: 'Quick Tip: If you use both Facebook and Instagram, changing the setting once in the Meta Accounts Center often applies to both apps at the same time.',
      },
      {
        title: 'Google: visit your Ad Center',
        content: 'Open a web browser and go to myadcenter.google.com, then sign in with your Google account. This page shows the topics Google thinks you are interested in based on your activity. You can turn off "Personalized ads" entirely with one switch, or remove individual topics one at a time if you want to keep some personalization.',
      },
      {
        title: 'Check your iPhone or Android privacy settings too',
        content: 'On iPhone, go to Settings, then Privacy & Security, then Apple Advertising, and turn off "Personalized Ads." On Android, go to Settings, then Privacy, then Ads, and turn on "Opt out of Ads Personalization" or reset your advertising ID. These settings limit tracking across every app on the device, not one company alone.',
      },
      {
        title: 'Understand what does not change',
        content: 'Turning off personalized ads reduces how targeted the ads feel, but it does not remove ads from free apps, and it does not stop the apps from collecting some data for their own operations. If you want to reduce tracking further, consider using a privacy-focused browser or search engine for sensitive searches.',
      },
    ],
  },

  {
    slug: 'set-up-bill-pay-reminder-alerts',
    title: 'How to Set Up Reminders So You Never Miss a Bill Payment',
    excerpt: 'A missed bill can mean a late fee or a ding on your credit. Here are three free ways to get reminded before a bill is due, using your phone, bank, or calendar.',
    category: 'financial-tech',
    tags: ['bills', 'reminders', 'budgeting', 'calendar', 'banking', 'money management'],
    readTime: '6 min',
    thumbnailEmoji: '📅',
    publishedAt: '2026-07-28',
    lastVerifiedAt: '2026-07-28',
    difficulty: 'Beginner',
    body: `A missed bill payment is usually not a sign of carelessness. It is a sign that nothing reminded you at the right moment. Most households juggle 8 to 12 different due dates a month — electric, water, phone, internet, insurance, credit cards — often with no single place listing them all. Setting up reminders solves this for good. It takes about 15 minutes to set up reminders for all your regular bills.

There are three good, free ways to do it, and they work best combined. Your bank or credit card company can text or email you a few days before a payment is due. Your phone's calendar app can hold a repeating reminder for each bill. And many billers — utility companies, insurance companies, phone carriers — offer their own free reminder texts or emails if you turn the feature on.

The calendar approach is the most reliable, because it does not depend on any one company's system working. If you set a repeating reminder for "Electric bill due — pay by the 15th" every month, it will keep showing up even if the power company's own alerts have a glitch that month.

For bills that never change in amount, like insurance or a phone plan, pair a reminder with automatic payment to remove the risk entirely. For bills that vary, like a credit card, keep the reminder but skip automatic payment — that way you can still check the amount before it is charged.

(Sources: Consumer Financial Protection Bureau — consumerfinance.gov; individual bank and biller apps)`,
    steps: [
      {
        title: 'List out your regular bills and due dates',
        content: 'Write down every recurring bill you pay and its due date: rent or mortgage, electric, water, gas, internet, phone, insurance, credit cards, and any subscriptions. Having the full list in one place, even on paper first, makes the next steps much easier.',
      },
      {
        title: 'Set up calendar reminders on your phone',
        content: 'Open your phone\'s Calendar app (Calendar on iPhone, Google Calendar on Android). Create a new event for each bill titled something like "Pay Electric Bill," set it a few days before the actual due date, and set it to repeat monthly. Turn on a notification alert for the morning of the event.',
        tip: 'Quick Tip: Set the reminder 3 to 5 days before the actual due date, not the day itself. This gives you a buffer if you need to transfer money between accounts first.',
      },
      {
        title: 'Turn on text or email alerts from your bank',
        content: 'Log into your bank or credit card\'s app or website and look for "Alerts," "Notifications," or "Account Settings." Most banks let you turn on a free text or email alert a few days before a scheduled bill payment or when your balance is low, which helps you avoid an overdraft.',
      },
      {
        title: 'Turn on reminders from individual billers',
        content: 'Many utility, insurance, and phone companies offer their own free reminder texts or emails. Log into each biller\'s app or website, look for "Notification Preferences" or "Communication Settings," and turn on due-date reminders. This adds a second layer of reminders beyond your calendar and bank.',
      },
      {
        title: 'Consider automatic payment only for fixed-amount bills',
        content: 'For bills that cost the same every month, like most insurance premiums or a phone plan, setting up automatic payment removes the risk of forgetting entirely. For bills that change in amount, like a credit card balance, keep a reminder without automatic payment so you can check the amount before it is charged.',
        warning: 'If you set up automatic payments, keep at least one reminder active anyway so you notice if a payment fails due to insufficient funds or an expired card.',
      },
    ],
  },
];
