// AUTO-GENERATED by scripts/generate-site-stats.mjs — do not edit by hand.
// Regenerated on every build (prebuild).
//
// These numbers used to be hardcoded in Landing.tsx, Tools.tsx and
// SiteIndex.tsx and had drifted badly (homepage claimed "2,500+ guides"
// against ~3748; /tools claimed "150+" against 2969). Stale numbers read
// as carelessness to a cautious audience. Use these constants in copy —
// never type a count literal into a component.

/** Exact counts at build time. */
export const GUIDE_COUNT = 3748;
export const TOOL_COUNT = 2969;

/** Display strings, rounded down so the claim is always true. */
export const GUIDE_COUNT_LABEL = '3,700+';
export const TOOL_COUNT_LABEL = '2,900+';
