export interface WikiPage {
  slug: string;
  title: string;
  category: 'concept' | 'entity' | 'synthesis' | 'source';
  tags: string[];
  content: string; // markdown content
  seeAlso: string[]; // slugs of related pages
  lastUpdated: string;
}

export const categoryLabels: Record<WikiPage['category'], string> = {
  concept: 'Concept',
  entity: 'Entity',
  synthesis: 'Synthesis',
  source: 'Source',
};

export const categoryColors: Record<WikiPage['category'], string> = {
  concept: 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300',
  entity: 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300',
  synthesis: 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300',
  source: 'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300',
};

export const wikiPages: WikiPage[] = [
  {
    slug: 'wifi-networking',
    title: 'Wi-Fi and Home Networking',
    category: 'concept',
    tags: ['wi-fi', 'internet', 'router', 'networking', 'home'],
    lastUpdated: '2026-04-01',
    seeAlso: ['password-security', 'safety-checklist', 'us-resources'],
    content: `## What Is Wi-Fi?

Wi-Fi is a wireless technology that lets your devices — phones, tablets, laptops, and smart TVs — connect to the internet without plugging in a cable. It uses radio signals sent by a device called a **router** in your home.

## How Your Home Network Works

Your internet setup has two main pieces:

- **Modem**: Connects your home to your internet provider (like Comcast, AT&T, or Spectrum). Think of it as the front door to the internet.
- **Router**: Takes that internet connection and shares it wirelessly with all your devices. Many providers give you a combined modem-router in one box.

## Common Wi-Fi Problems and Fixes

**Slow internet?** Try these steps:
1. Move closer to your router — walls and distance weaken the signal.
2. Restart your router by unplugging it for 30 seconds, then plugging it back in.
3. Make sure no one is downloading large files or streaming on multiple devices at once.

**Can't connect?** Check that:
1. Wi-Fi is turned on in your device settings.
2. You are selecting the correct network name.
3. You are entering the password correctly (it is case-sensitive).

## Keeping Your Wi-Fi Secure

- Change the default router password — the one printed on the sticker is known to attackers.
- Use WPA3 or WPA2 encryption (your router settings will show this option).
- Do not share your Wi-Fi password with people you do not trust.
- Consider setting up a guest network for visitors.

## Quick Tip

Your router's network name and password are usually printed on a sticker on the bottom or back of the device. If you have changed them and forgotten, you can reset the router to factory settings by pressing and holding the small reset button for 10 seconds.`,
  },
  {
    slug: 'password-security',
    title: 'Password Security',
    category: 'concept',
    tags: ['passwords', 'security', 'accounts', '2fa', 'authentication'],
    lastUpdated: '2026-04-02',
    seeAlso: ['scam-prevention', 'safety-checklist', 'wifi-networking'],
    content: `## Why Passwords Matter

Your password is the lock on your digital front door. A weak or reused password is like using the same key for your house, car, and office — if someone copies it once, they can get into everything.

## What Makes a Strong Password

A strong password has three qualities:
- **Long**: At least 12 characters. Longer is better.
- **Unique**: Different for every account. Never reuse passwords.
- **Unpredictable**: Avoid names, birthdays, pet names, or common words like "password123."

A great method is to use a **passphrase** — a string of random words, like "purple-telescope-garden-42." It is long, memorable, and hard to guess.

## Password Managers

A password manager is an app that creates, stores, and fills in strong passwords for you. You only need to remember one master password to unlock the manager itself.

Popular options include:
- **Bitwarden** (free, open-source)
- **1Password** (paid, very user-friendly)
- **Apple Keychain** (built into iPhones and Macs)
- **Google Password Manager** (built into Chrome and Android)

## Two-Factor Authentication (2FA)

Two-factor authentication adds a second layer of protection. After entering your password, you also enter a short code sent to your phone or generated by an app. Even if someone steals your password, they cannot log in without that second code.

Turn on 2FA for your most important accounts first: email, banking, and social media.

## What to Do If You Think Your Password Was Stolen

1. Change the password for that account right away.
2. Check if your email appears on [Have I Been Pwned](https://haveibeenpwned.com) — a free tool that tells you if your information was part of a data breach.
3. Turn on 2FA if you have not already.
4. Watch your bank and credit card statements for anything you did not authorize.`,
  },
  {
    slug: 'scam-prevention',
    title: 'Scam Prevention',
    category: 'concept',
    tags: ['scams', 'phishing', 'safety', 'fraud', 'email'],
    lastUpdated: '2026-04-03',
    seeAlso: ['password-security', 'safety-checklist', 'us-resources'],
    content: `## The Most Common Tech Scams

Scammers use technology to trick people into handing over money or personal information. Here are the most common types:

### Phishing Emails and Texts
You receive a message that looks like it is from a trusted company — your bank, Amazon, or the IRS. It asks you to click a link and enter your login details. The link leads to a fake website that steals your information.

**How to spot it:** Look for misspellings, urgent language ("Your account will be closed!"), and suspicious sender addresses. Hover over links before clicking to see where they actually go.

### Tech Support Scams
A pop-up appears on your screen saying your computer has a virus and you must call a number right away. The person who answers pretends to be from Microsoft or Apple and asks for remote access to your computer or payment to "fix" the problem.

**How to spot it:** Real tech companies will never show you a pop-up with a phone number or ask for remote access out of the blue.

### Phone Scams (Vishing)
A caller claims to be from the IRS, Social Security, or your bank. They threaten arrest, fines, or account closure unless you pay immediately — often with gift cards or wire transfers.

**How to spot it:** Government agencies do not call and demand immediate payment. Hang up and call the official number from the agency's website.

## Golden Rules of Scam Prevention

1. **Never rush.** Scammers create urgency to stop you from thinking clearly.
2. **Never give remote access** to someone who contacts you first.
3. **Never pay with gift cards.** No real company or government agency accepts gift cards as payment.
4. **Verify independently.** If a message claims to be from your bank, hang up and call the number on the back of your card.
5. **Talk to someone you trust** before acting on anything that feels off.

## Where to Report Scams
- **FTC**: [ReportFraud.ftc.gov](https://reportfraud.ftc.gov)
- **FBI Internet Crime**: [IC3.gov](https://ic3.gov)
- **AARP Fraud Helpline**: 1-877-908-3360`,
  },
  {
    slug: 'beginners-roadmap',
    title: 'Beginner\'s Tech Roadmap',
    category: 'synthesis',
    tags: ['beginner', 'getting-started', 'learning', 'roadmap'],
    lastUpdated: '2026-04-01',
    seeAlso: ['wifi-networking', 'password-security', 'safety-checklist', 'us-resources'],
    content: `## Your First Steps with Technology

Learning technology does not have to feel overwhelming. This roadmap breaks the journey into small, manageable steps. Go at your own pace — there is no deadline.

## Week 1-2: The Basics

Start with the device you use most (phone, tablet, or computer) and practice these essentials:

- **Turning your device on and off** — find the power button and learn the difference between sleep mode and shutting down completely.
- **Using the touchscreen or mouse** — practice tapping, swiping, scrolling, and clicking.
- **Adjusting settings** — make the text bigger, turn the brightness up or down, and adjust the volume.
- **Connecting to Wi-Fi** — open your settings, find Wi-Fi, select your home network, and enter the password.

## Week 3-4: Communication

Once you are comfortable with the basics, learn to stay in touch:

- **Making phone calls and video calls** — try FaceTime (iPhone) or Google Meet (Android and computers).
- **Sending text messages** — practice typing messages and adding photos.
- **Using email** — set up a Gmail or Outlook account, send a test email to a family member.

## Week 5-6: Staying Safe Online

Before exploring further, learn how to protect yourself:

- **Create strong passwords** for every account (see our Password Security page).
- **Recognize scams** — learn the warning signs (see our Scam Prevention page).
- **Keep your device updated** — turn on automatic updates so your device always has the latest security fixes.

## Week 7-8: Exploring More

Now that you have a solid foundation:

- **Browse the web** — practice searching on Google and bookmarking your favorite sites.
- **Download helpful apps** — weather, news, health tracking, and video calling.
- **Try online shopping** — start with a trusted site like Amazon and use a credit card (not debit) for extra fraud protection.

## Quick Tip

Write down your passwords in a notebook you keep in a safe place at home. This is a perfectly fine approach while you are getting started — you can switch to a password manager later when you are ready.`,
  },
  {
    slug: 'safety-checklist',
    title: 'Digital Safety Checklist',
    category: 'synthesis',
    tags: ['safety', 'checklist', 'security', 'privacy', 'best-practices'],
    lastUpdated: '2026-04-02',
    seeAlso: ['password-security', 'scam-prevention', 'wifi-networking'],
    content: `## Your Personal Digital Safety Checklist

Use this checklist to make sure your devices and accounts are secure. You do not need to do everything at once — work through it one item at a time.

## Passwords and Accounts

- [ ] Every account has a unique password (not reused anywhere else)
- [ ] All passwords are at least 12 characters long
- [ ] Two-factor authentication is turned on for email, banking, and social media
- [ ] You have a way to store passwords safely (notebook in a secure place, or a password manager)
- [ ] You have a recovery email or phone number set up for your most important accounts

## Device Security

- [ ] Your phone has a lock screen with a PIN, fingerprint, or face recognition
- [ ] Your computer requires a password to log in
- [ ] Automatic updates are turned on for your operating system
- [ ] Automatic updates are turned on for your apps
- [ ] You have antivirus software installed (Windows Defender is built into Windows and works well)

## Wi-Fi and Network

- [ ] Your home Wi-Fi has a strong password (not the default one from the sticker)
- [ ] Your router uses WPA2 or WPA3 encryption
- [ ] You have a separate guest network for visitors (if your router supports it)
- [ ] You avoid doing banking or shopping on public Wi-Fi without a VPN

## Email and Browsing

- [ ] You do not click links in unexpected emails or texts
- [ ] You check the sender's email address before responding to messages
- [ ] You look for the padlock icon in your browser's address bar before entering personal information
- [ ] You have an ad blocker installed in your browser (uBlock Origin is a good free option)

## Backups

- [ ] Important photos are backed up (to iCloud, Google Photos, or an external drive)
- [ ] Important documents are backed up in a second location
- [ ] You know how to restore from a backup if something goes wrong

## Quick Tip

Set a calendar reminder once every three months to review this checklist. Technology changes, and a quick review helps you stay protected.`,
  },
  {
    slug: 'us-resources',
    title: 'U.S. Tech Help Resources',
    category: 'entity',
    tags: ['resources', 'help', 'government', 'organizations', 'support'],
    lastUpdated: '2026-04-03',
    seeAlso: ['scam-prevention', 'beginners-roadmap', 'safety-checklist'],
    content: `## Free and Trusted Tech Help in the United States

You do not have to figure out technology alone. These organizations offer free help, guides, and support designed for people who are still learning.

## Government Resources

### Federal Trade Commission (FTC)
- **Website**: [ftc.gov/consumers](https://consumer.ftc.gov)
- **What they offer**: Consumer protection information, scam alerts, and a fraud reporting tool.
- **Report scams**: [ReportFraud.ftc.gov](https://reportfraud.ftc.gov)

### Cybersecurity and Infrastructure Security Agency (CISA)
- **Website**: [cisa.gov](https://www.cisa.gov)
- **What they offer**: Cybersecurity tips for individuals and families, alerts about current threats.

### FBI Internet Crime Complaint Center (IC3)
- **Website**: [ic3.gov](https://www.ic3.gov)
- **What they offer**: A place to report internet-related crimes including fraud, identity theft, and hacking.

## Nonprofit Organizations

### AARP
- **Website**: [aarp.org/technology](https://www.aarp.org/home-family/personal-technology/)
- **What they offer**: Tech guides written for adults 50+, free webinars, and a fraud helpline (1-877-908-3360).
- **Best for**: Learning at your own pace with step-by-step articles.

### GCFGlobal (Goodwill Community Foundation)
- **Website**: [gcfglobal.org](https://edu.gcfglobal.org/en/topics/technology/)
- **What they offer**: Free online courses covering computers, smartphones, the internet, and essential software.
- **Best for**: Structured learning from the very beginning.

## Local Help

### Public Libraries
Most public libraries offer:
- Free Wi-Fi and computer access
- One-on-one tech help sessions with librarians
- Group classes on topics like email, internet safety, and using a smartphone

Call your local library to ask about their technology programs.

### Senior Centers
Many senior centers host regular technology classes. Contact your local Area Agency on Aging at [eldercare.acl.gov](https://eldercare.acl.gov) or call 1-800-677-1116 to find programs near you.

## Quick Tip

AARP membership is not required to access their free online tech guides and videos. Anyone can visit [aarp.org/technology](https://www.aarp.org/home-family/personal-technology/) and start learning right away.`,
  },
];

/** Look up a wiki page by slug */
export function getWikiPage(slug: string): WikiPage | undefined {
  return wikiPages.find(p => p.slug === slug);
}
